### ISSUE TITLE
tbox 在向某款嵌入式linux平台移植，进行配置时报错

### ISSUE THREAD

**Issue by aseing-0** [tboox/tbox#100]
### 描述问题

tbox工程移植嵌入式平台时，按照文档中进行配置时，报错。
tbox 版本信息：
c
[log.txt](https://github.com/tboox/tbox/files/3569243/log.txt)
ommit 0cdb41ee2f944466e4d69219922f2feb5b761514 (HEAD -> master, origin/master, origin/HEAD)
Author: ruki <waruqi@gmail.com>
Date:   Sat Aug 17 00:48:37 2019 +0800

    set process private data

执行命令：xmake f -p cross  --sdk=/home/esuny/soft/arm-2009q3/  --bin=/home/esuny/soft/arm-2009q3/bin --cross=arm-none-linux-gnueabi-   -v -D
### 错误信息
见附件
### 相关环境
os： ubuntu-18.04
cross-tool: 
arm-none-linux-gnueabi-gcc  -v
Using built-in specs.
Target: arm-none-linux-gnueabi
Configured with: /scratch/julian/2009q3-respin-linux-lite/src/gcc-4.4/configure --build=i686-pc-linux-gnu --host=i686-pc-linux-gnu --target=arm-none-linux-gnueabi --enable-threads --disable-libmudflap --disable-libssp --disable-libstdcxx-pch --enable-extra-sgxxlite-multilibs --with-arch=armv5te --with-gnu-as --with-gnu-ld --with-specs='%{funwind-tables|fno-unwind-tables|mabi=*|ffreestanding|nostdlib:;:-funwind-tables} %{O2:%{!fno-remove-local-statics: -fremove-local-statics}} %{O*:%{O|O0|O1|O2|Os:;:%{!fno-remove-local-statics: -fremove-local-statics}}}' --enable-languages=c,c++ --enable-shared --disable-lto --enable-symvers=gnu --enable-__cxa_atexit --with-pkgversion='Sourcery G++ Lite 2009q3-67' --with-bugurl=https://support.codesourcery.com/GNUToolchain/ --disable-nls --prefix=/opt/codesourcery --with-sysroot=/opt/codesourcery/arm-none-linux-gnueabi/libc --with-build-sysroot=/scratch/julian/2009q3-respin-linux-lite/install/arm-none-linux-gnueabi/libc --with-gmp=/scratch/julian/2009q3-respin-linux-lite/obj/host-libs-2009q3-67-arm-none-linux-gnueabi-i686-pc-linux-gnu/usr --with-mpfr=/scratch/julian/2009q3-respin-linux-lite/obj/host-libs-2009q3-67-arm-none-linux-gnueabi-i686-pc-linux-gnu/usr --with-ppl=/scratch/julian/2009q3-respin-linux-lite/obj/host-libs-2009q3-67-arm-none-linux-gnueabi-i686-pc-linux-gnu/usr --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --with-cloog=/scratch/julian/2009q3-respin-linux-lite/obj/host-libs-2009q3-67-arm-none-linux-gnueabi-i686-pc-linux-gnu/usr --disable-libgomp --enable-poison-system-directories --with-build-time-tools=/scratch/julian/2009q3-respin-linux-lite/install/arm-none-linux-gnueabi/bin --with-build-time-tools=/scratch/julian/2009q3-respin-linux-lite/install/arm-none-linux-gnueabi/bin
Thread model: posix
gcc version 4.4.1 (Sourcery G++ Lite 2009q3-67) 

请提供其他附加信息帮助我们诊断问题。

**Comment by waruqi** [comment]
你把-p cross改成 -p linux试试 tbox里面用了 $(os) 变量 -p cross 下取不到所以报错了

**Comment by aseing-0** [comment]
1.pid_t 这个变量不存在。
2.不支持匿名的联合体 union{xxxxx} 
3.不支持'yield'            
  --是不是需要删减某些该系统不支持的 tbox的功能？
(1和2的错误，我为了能够编译通过，自己修改了）
error: /tmp/ccxreXaK.s: Assembler messages:
/tmp/ccxreXaK.s:348: Error: selected processor does not support `yield'
/tmp/ccxreXaK.s:459: Error: selected processor does not support `yield'
/tmp/ccxreXaK.s:538: Error: selected processor does not support `yield'
/tmp/ccxreXaK.s:643: Error: selected processor does not support `yield'
/tmp/ccxreXaK.s:736: Error: selected processor does not support `yield'
/tmp/ccxreXaK.s:827: Error: selected processor does not support `yield'
/tmp/ccxreXaK.s:914: Error: selected processor does not support `yield'

**Comment by waruqi** [comment]
https://github.com/tboox/tbox/blob/0cdb41ee2f944466e4d69219922f2feb5b761514/src/tbox/platform/cpu.h#L62-L69

这块你注释掉试试，这几个错误也是后来改动代码 新加的，所以交叉编译下没怎么测过，难免有些编译错误，回头我处理下，你先临时改改试试吧。

**Comment by aseing-0** [comment]
注释掉那一块后 信息如下
```
[ 38%]: compiling.release src/tbox/platform/cache_time.c
[ 38%]: compiling.release src/tbox/network/dns/looker.c
[ 38%]: compiling.release src/tbox/network/impl/http/option.c
[ 39%]: compiling.release src/tbox/libc/stdlib/wcstombs.c
[ 39%]: compiling.release src/tbox/platform/process.c
error: src/tbox/platform/posix/process.c:143: error: 'struct __tb_process_attr_t' has no member named 'outpath'
src/tbox/platform/posix/process.c:146: error: 'struct __tb_process_attr_t' has no member named 'outpath'
In file included from src/tbox/platform/process.c:40:
src/tbox/platform/posix/process.c:149: error: 'struct __tb_process_attr_t' has no member named 'outpipe'
src/tbox/platform/posix/process.c:150: error: 'struct __tb_process_attr_t' has no member named 'outfile'
src/tbox/platform/posix/process.c:153: error: 'struct __tb_process_attr_t' has no member named 'outpipe'
src/tbox/platform/posix/process.c:153: error: 'struct __tb_process_attr_t' has no member named 'outpipe'
src/tbox/platform/posix/process.c:153: error: 'struct __tb_process_attr_t' has no member named 'outfile'
src/tbox/platform/posix/process.c:153: error: 'struct __tb_process_attr_t' has no member named 'outfile'
src/tbox/platform/posix/process.c:159: error: 'struct __tb_process_attr_t' has no member named 'errpath'
src/tbox/platform/posix/process.c:162: error: 'struct __tb_process_attr_t' has no member named 'errpath'
src/tbox/platform/posix/process.c:165: error: 'struct __tb_process_attr_t' has no member named 'errpipe'
src/tbox/platform/posix/process.c:166: error: 'struct __tb_process_attr_t' has no member named 'errfile'
src/tbox/platform/posix/process.c:169: error: 'struct __tb_process_attr_t' has no member named 'errpipe'
src/tbox/platform/posix/process.c:169: error: 'struct __tb_process_attr_t' has no member named 'errpipe'
src/tbox/platform/posix/process.c:169: error: 'struct __tb_process_attr_t' has no member named 'errfile'
src/tbox/platform/posix/process.c:169: error: 'struct __tb_process_attr_t' has no member named 'errfile'
```

**Comment by waruqi** [comment]
你这个是该匿名union 没改对吧。。所以有这个错误。。

**Comment by waruqi** [comment]
你可以更新下dev分支，2,3 我刚修了下，应该可以了。。

xmake f 配置的时候，加上-c重新检测下配置后，再编译试试

```console
xmake f -p linux --sdk=/home/esuny/soft/arm-2009q3/ --bin=/home/esuny/soft/arm-2009q3/bin --cross=arm-none-linux-gnueabi- -c 
xmake
```

**Comment by aseing-0** [comment]
OK，我直接不使用联合体了，应该没问题吧。只是空间会浪费点呗。
编译demo的时候报错，这个c++的选项我没找到在哪里修改掉。
```
[ 61%]: compiling.release src/demo/platform/filelock.c
[ 62%]: compiling.release src/demo/libc/wcstombs.c
[ 99%]: compiling.release src/demo/other/test.cpp
error: cc1plus: error: unrecognized command line option "-std=c++11"
```

**Comment by waruqi** [comment]
> OK，我直接不使用联合体了，应该没问题吧。只是空间会浪费点呗。

你更新到dev分支就行了，我刚加了个匿名union检测支持，如果当前编译器不支持，会自动退化到不使用的情况的。。

> 编译demo的时候报错，这个c++的选项我没找到在哪里修改掉。
> 
> ```
> [ 61%]: compiling.release src/demo/platform/filelock.c
> [ 62%]: compiling.release src/demo/libc/wcstombs.c
> [ 99%]: compiling.release src/demo/other/test.cpp
> error: cc1plus: error: unrecognized command line option "-std=c++11"
> ```

这个在跟目录xmake.lua里面设置的，set_languages里面，删了就行了

不过也就一个demo cpp文件，用户测试c++下集成tbox的，，所以只要不编译demo就可以了。。

xmake f --demo=n 禁用demo编译即可。

**Comment by aseing-0** [comment]
新增的宏 TB_CONFIG_FEATURE_HAVE_ANONYMOUS_UNION 没有生效啊。匿名union那个地方还是报错了。

另，我对pid_t那个地方的修改是，直接把(pid_t) 给去掉。 不在这里强转。

**Comment by aseing-0** [comment]
```...
  > replace TB_CONFIG_KEYWORD_HAVE__thread -> #define TB_CONFIG_KEYWORD_HAVE__thread 1
  > replace TB_CONFIG_KEYWORD_HAVE_Thread_local -> /* #undef TB_CONFIG_KEYWORD_HAVE_Thread_local */
  > replace TB_CONFIG_FEATURE_HAVE_ANONYMOUS_UNION -> #define TB_CONFIG_FEATURE_HAVE_ANONYMOUS_UNION 1
...
```

**Comment by waruqi** [comment]
> 新增的宏 TB_CONFIG_FEATURE_HAVE_ANONYMOUS_UNION 没有生效啊。匿名union那个地方还是报错了。

居然检测通过了。。= =

> 
> 另，我对pid_t那个地方的修改是，直接把(pid_t) 给去掉。 不在这里强转。

你可以试试加头文件是否能通过，比如 sys/types.h 等，或者到你的工具链include下搜下，有没有pid_t的定义。。

**Comment by waruqi** [comment]
你这工具链能发我一份吗？ 我看下 为啥能检测通过

**Comment by aseing-0** [comment]
工具链发你QQ邮箱了

**Comment by waruqi** [comment]
收到，你这边先临时改改吧，回头我抽空适配下

**Comment by waruqi** [comment]
你再更新下dev试试，应该都能通过了

**Comment by aseing-0** [comment]
编译通过。
