### ISSUE TITLE
wyhash函数和wyrand随机数发生器

### ISSUE THREAD

**Issue by wangyi-fudan** [tboox/tbox#102]
### 你在什么场景下需要该功能？

我们需要最快速最简洁优雅的高质量哈希函数和随机数发生器。

### 描述可能的解决方案

希望把我开发的wyhash库加入tbox，该库已得到主流测试认可(SMHasher,BigCrush)，已有150星。
https://github.com/wangyi-fudan/wyhash

谢谢！

**Comment by waruqi** [comment]
很棒的库，不过tbox暂时不打算增加对外部库的依赖。

如果你愿意把源码集成进https://github.com/tboox/tbox/tree/master/src/tbox/hash，并且接口定义，代码风格，以及类型系统全部切换到跟tbox保持一致，可以提个pr过来，具体可参考：https://github.com/tboox/tbox/blob/master/src/tbox/hash/fnv64.c

并且还需要保证代码在没有引用其他第三方依赖的情况，保证：win/linux/ios/android/mingw/macos下都可正常编译，以及正常运行。。
