### ISSUE TITLE
使用xmake执行多次xmake遇到问题

### ISSUE THREAD

**Issue by tjy-cool** [tboox/tbox#103]
###  问题一 首次xmake成功，删除bulid目录后执行xmake报错

1.  操作步骤

- 执行最小编译

`xmake f --small=y; xmake`

- 删除生成的build目录
`rm -rf build`

- 再次执行xmake

`xmake`

2. 报错

`[  0%]: compiling.release src/tbox/string/static_string.c
[  0%]: compiling.release src/tbox/platform/sched.c
[  0%]: compiling.release src/tbox/stream/stream.c
[  0%]: compiling.release src/tbox/utils/base32.c
[  0%]: compiling.release src/tbox/libc/stdio/wprintf.c
[  0%]: compiling.release src/tbox/libc/string/wcscat.c
error: src/tbox/platform/../prefix/../config.h:27:10: fatal error: 'tbox.config.h' file not found
#include "tbox.config.h"
         ^~~~~~~~~~~~~~~
1 error generated.`

###  问题二 如果删除build目录后，执行make也报错

1.  操作步骤

- 执行xmake project生成Makefile

`xmake project -k makefile`

- 执行make
`make`

- 删除build目录

`rm -rf build `

2. 问题

再次执行make报错

`compiling.release src/tbox/string/static_string.c
make: *** [build/.objs/tbox/macosx/x86_64/release/src/tbox/string/static_string.c.o] Error 1`

-----
>  想问下为什么不能删除build目录呢，按照正常来说，build目录只是一个生成后的目录，删除不应该对`xmake`或`make`命令产生影响。
> 如果真的产生影响，该如何像Makefile中的`make clean` 自定义删除一些东西呢，我尝试使用`xmake clean`，但是不起作用，问下该如何编写`xmake clean`才能其作用呢?

**Comment by waruqi** [comment]
因为tbox里面tbox.config.h是执行xmake f -c时候自动生成的，我目前配置在build里面，所以会有干扰，如果配置到其他目录就不会有这问题

你可以追加-c到xmake f -c xxx，每次配置变动的时候，强制重新生成tbox.config.h，否则默认配置没变用了缓存配置，不会重新生成，假定config.h已经存在，避免影响增量编译依赖变动导致rebuild

这个只是tbox里面的xmake.lua配置问题，目前我觉得生成在build影响不大，你可以使用xmake clean --all 来清理所有，包括整个build

默认的xmake clean只会清理临时文件，比如obj deps等，对于target file以及config file默认不会清理

如果还要定制clean 你可以在 xmake.lua加上 after_clean里面去自定义清理文件，这块可以看下文档: 
https://xmake.io/#/zh-cn/manual/project_target?id=targetafter_clean

**Comment by tjy-cool** [comment]
问题解决，谢谢
