### ISSUE TITLE
tbox可以用cmake来编译吗？

### ISSUE THREAD

**Issue by 751643992** [tboox/tbox#105]
tbox可以用cmake来编译吗？

**Comment by waruqi** [comment]
用xmake生成cmakelists

xmake project -k cmakelists

**Comment by 751643992** [comment]
明白，我的意思是把tbox源代码作为开发，如果把tbox编译成静态库或者动态库，很容易被破解（hook导出函数），而且ollvm无法混淆静态库和动态库，我想把tbox集成到android平台做native层开发。

**Comment by waruqi** [comment]
你生成了cmakelists.txt 不就可以集成过去了么？

**Comment by 751643992** [comment]
明白了原来xmake生成带有cmakelists.txt 的tbox，好的，感谢。
