### ISSUE TITLE
用xmake生成vs工程，不支持Micro编译模式

### ISSUE THREAD

**Issue by tangaoo** [tboox/tbox#106]
### 描述问题

xmake project -k vsxmake -m "micro” 生成了vs2019工程，然后在vs中编译生成的tbox.lib有1315k大小，与small模式大小一样，应该并没有真正生成micro模式下lib；而用命令行通过xmake menu选中使能micro，然后直接xmake编译，生成的tbox.lib大小是200多k。应该是正在开启了micro模式。

### 期待的结果

在VS2019中可以编译tbox的Micro模式。

### 相关环境

xmake:v2.2.8  tbox:1.6.4   vs:vs2019

**Comment by tangaoo** [comment]
在补充一点，micro模式生成的tbox.lib大小200多k，比文档讲64k左右要大很多，不知道是什么原因？

**Comment by waruqi** [comment]
编译模式，debug/release才叫mode，通过`xmake f -m debug/release`切换，也可在xmake project传入使用

micro/small属于tbox自定义的选项，有独立自定义的配置参数：`xmake f --micro=y/n --small=y/n` , 并不是 `-m/--mode`的编译模式参数。

readme里面的`模式`说明，我只是随手的写中文统称，方便理解而已。

```console
xmake f --micro=y
xmake project -k vsxmake
```

**Comment by tangaoo** [comment]
@waruqi 感谢抽空回复，已明白。任有两个问题。

1. 编译报错。
```
    xmake f --micro=y -c
    xmake project -k vsxmake
```
确实是micro了，main函数也是调用的micro.c里面的了，但最后link的时候报错，存缺下面两个函数，我暂时把他们屏蔽了。
```
    tb_windows_init_env(void)
    tb_windows_exit_env(void)
```
2. 如何切换到debug模式。
```
    xmake f --micro=y -c
    xmake project -k vsxmake -m debug
```
如上命令执行后，虽然生成了debug模式，但是micro配置项被清除了。如何实现debug模式下的micro？

**Comment by waruqi** [comment]
> 确实是micro了，main函数也是调用的micro.c里面的了，但最后link的时候报错，存缺下面两个函数，我暂时把他们屏蔽了。

这个我回头处理下

> 如上命令执行后，虽然生成了debug模式，但是micro配置项被清除了。如何实现debug模式下的micro？

是指micro没生效？

**Comment by waruqi** [comment]
> 确实是micro了，main函数也是调用的micro.c里面的了，但最后link的时候报错，存缺下面两个函数，我暂时把他们屏蔽了。

这个问题我dev上修复了。

> 如上命令执行后，虽然生成了debug模式，但是micro配置项被清除了。如何实现debug模式下的micro？

我测了下，没啥问题啊，好好的，vsproj能正常编译micro/debug

**Comment by tangaoo** [comment]
感谢 @waruqi 回复。2个问题均解决。
