### ISSUE TITLE
如何查看Micro模式下编译，具体是包含了哪些模块，哪些c文件？

### ISSUE THREAD

**Issue by tangaoo** [tboox/tbox#107]
把tbox用在嵌入式平台上，micro模式包含了最小微内核，但想进一步知道具体包含哪些模块，哪些C文件？是否可以从xmake的编译配置文件中看出？

xmake:v2.2.8 tbox:1.6.4 vs:vs2019

**Comment by waruqi** [comment]
看里面的micro.lua

**Comment by tangaoo** [comment]
@waruqi 感谢抽空回复
