### ISSUE TITLE
tbox代码组织架构的问题？

### ISSUE THREAD

**Issue by tangaoo** [tboox/tbox#108]
@waruqi tbox库非常棒，最近在读源码，有些不理解的地方，在这里提问不知是否合适。

1. impl文件夹
每个模块基本都包含impl文件夹，里面基本包含模块的init、exit。但是memory模块里的impl文件夹里又包含很多其他接口，被同级目录下.c文件调用。所以请教下这个impl的设定是什么逻辑？

**Comment by waruqi** [comment]
> @waruqi tbox库非常棒，最近在读源码，有些不理解的地方，在这里提问不知是否合适。
> 
> 1. impl文件夹
>    每个模块基本都包含impl文件夹，里面基本包含模块的init、exit。但是memory模块里的impl文件夹里又包含很多其他接口，被同级目录下.c文件调用。所以请教下这个impl的设定是什么逻辑？

一些私有接口的定义和实现，都会放置到impl，确保不会对外开放，xmake.lua提取头文件发布时候，也会忽略所有impl目录下的头文件
