### ISSUE TITLE
多线程使用内置式链表问题

### ISSUE THREAD

**Issue by jacob1024** [tboox/tbox#109]
> Note: 内置式链表

### Describe the bug
多线程添加链表元素出错。嵌入式linux平台

code:

tb_list_ref_t   listTest = tb_null;

void*  FS_LIST_PthreadFunc1(void* args)
{
    pthread_detach(pthread_self());

    /* 插入第二个元素 */
    tb_list_insert_tail(listTest, "BBBBBBBBBB");
    
    while(1)
    {
        sleep(1);
    }
    
    pthread_exit(NULL);
}

void*  FS_LIST_PthreadFunc2(void* args)
{
    pthread_detach(pthread_self());

    /* 插入第三个元素 */
    tb_list_insert_tail(listTest, "CCCCCCCCCC");
    
    while(1)
    {
        sleep(1);
    }
    
    pthread_exit(NULL);
}

/* list多线程测试 */

void FS_LIST_PthreadTest()
{
    /* 初始化 */
    pthread_t pid1;
    pthread_t pid2;

    listTest = tb_list_init(0, tb_element_str(tb_true));

    /* 插入第一个元素A */
    tb_list_insert_tail(listTest, "AAAAAAAAAA");

    /* 开启第一个线程,插入第二个元素  */
    if (pthread_create(&pid1, NULL, FS_LIST_PthreadFunc1, NULL) < 0)
    {
        printf("create  thread 1 fail \n");
    }

    sleep(1);

    /* 开启第二个线程,插入第三个元素  */
    if (pthread_create(&pid2, NULL, FS_LIST_PthreadFunc2, NULL) < 0)
    {
        printf("create  thread 2 fail \n");
    }

    tb_for_all (tb_char_t*, item, listTest)
    {
        tb_trace_i("str: %s", item);
    }

    getchar();
    getchar();
    
}

实际输出:
str AAAAAAAAAA
str BBBBBBBBBBB

希望输出
str AAAAAAAAAA
str BBBBBBBBBBB
str CCCCCCCCCC

**Comment by waruqi** [comment]
1. tbox里面所有容器都不是线程安全的，你得自己加锁控制，你这么搞，跑不了多久就得崩
2. 线程不是你create了就能立马运行的，你最后一个create后立马去forall了，thread2都还没跑起来，你已经print list了 ，怎么可能看的到ccccc

**Comment by jacob1024** [comment]
非常感谢！问题看起来已经解决。

1，工作的代码是加锁控制的。

2，工作的代码， 我是要在thread2 中去print list。问题是使用forall的方式无法打印出所有的元素，只能打印出一个元素。改为迭代器遍历的方式就可以打印出所有的元素。现在还不知道这是什么原因。

**Comment by waruqi** [comment]
> 工作的代码， 我是要在thread2 中去print list。问题是使用forall的方式无法打印出所有的元素，只能打印出一个元素。改为迭代器遍历的方式就可以打印出所有的元素。现在还不知道这是什么原因。

那你也得给个能复现的demo，我才能给你看。要么你自己到tbox代码里面调下吧。。

**Comment by waruqi** [comment]
forall为了考虑到效率，for之前提前保存的tail迭代器，所以如果是在遍历过程中，又新增了元素，这种情况是语法遍历到新元素的，因为tail已经提前保存了。

如果需要在遍历过程中不断地增删元素，建议不要用for，自己用迭代器迭代，确保每次重新获取tail迭代器位置。

**Comment by jacob1024** [comment]
那么在一般的遍历，只是获取元素，就可以用forall ：)

我现在删除和新增操作都使用迭代器操作了。

**Comment by waruqi** [comment]
只要你遍历的过程中间 肯定不会存在 插入和删除操作，那么就可以用forall，如果存在，建议用迭代器
