### ISSUE TITLE
Linux backtrace 无符号

### ISSUE THREAD

**Issue by codehz** [tboox/tbox#113]
### 描述问题

任意位置触发dump
将会看到类似这样的结果
![image](https://user-images.githubusercontent.com/13158903/70885510-fe3b7b80-2013-11ea-98df-dc528448c210.png)
其中只有第一个地址有准确的符号
后面的所有地址都是没有符号的
这对调试很不利

### 期待的结果

正确显示backtrace符号

### 错误信息

（并不是编译期错误）

### 相关环境

OS: Arch Linux (x86_64)
tbox: https://github.com/tboox/tbox/commit/36908b0a998fd122ae936a8d0b3e824c09889873

### 其他信息

gdb/lldb中可正确显示

**Comment by waruqi** [comment]
这个我回头抽空查下。

**Comment by waruqi** [comment]
我修复了，linux下通过backtrace_symbols获取符号得加 `-rdynamic ` ldflags才行。 可以更新到dev试试
