### ISSUE TITLE
printf等函数可以加上一些attribute让gcc/clang等编译器参与检查

### ISSUE THREAD

**Issue by codehz** [tboox/tbox#115]
### 你在什么场景下需要该功能？

具体就是printf这类函数容易由于疏漏写参数，而gcc/clang恰好内置了检查功能，只需要加上类似
`__attribute__ ((format (printf, 1, 2)));`
这样的attribute就能启用编译器内置检查，可以大大降低某些失误造成的错误。

### 描述可能的解决方案

给相关函数加上检查（当然要进行编译器检查，只给__GNUC__的开放）

### 其他信息

虽然是gcc扩展，但是它首先不会影响功能，不会改变编译结果，其次支持比较广，很多低版本编译器就已采用。
https://gcc.gnu.org/onlinedocs/gcc-3.2/gcc/Function-Attributes.html
https://releases.llvm.org/3.7.0/tools/clang/docs/AttributeReference.html
这个特性至少在gcc 3.2和clang 3.7时代就有了，可以认为只要存在__GNUC__就可以启用

**Comment by waruqi** [comment]
tb_printf的格式标准是tbox扩展过的，并不完全适配原生编译器，不太好做检测，暂时先不加了吧~
