### ISSUE TITLE
xmake-repo上的xmake.lua有bug

### ISSUE THREAD

**Issue by eddylin83** [tboox/tbox#117]
### 问题
添加tbox依赖出错：`add_requires("tbox",{configs = {micro = true}})`，看了一下提示，44行出现nil value，将从xmake-repo缓存的tbox的xmake.lua第44行改为`configs.micro = true`(即config.micro改为configs.micro)即可。同理，测试了一下，定义float的时候一样出错，需要将47行改为`configs["float"]`，所以50行的`config["force-utf8"] `应该也要修改。

**Comment by waruqi** [comment]
好的，回头我看下

**Comment by waruqi** [comment]
我修复了，之后关于xmake-repo的问题，可以直接提到xmake-repo/issues上去，或者直接帮忙提个pr就好。
