### ISSUE TITLE
micro精简得凶了一点

### ISSUE THREAD

**Issue by eddylin83** [tboox/tbox#118]
mutex那些都不能用了，这部分代码编译应该没问题吧？如果没调用的话应该可以strip掉的。如果micro不打算加上这些，或者哪里可以自己加上先用着？

**Comment by waruqi** [comment]
可以锁粒度弄小些，然后用spinlock代替，这个可以用，因为定义在头文件里，只用到了atomic

**Comment by waruqi** [comment]
我dev上mutex和semaphore加上了
