### ISSUE TITLE
tb_lo_coroutine_func_t 类型问题

### ISSUE THREAD

**Issue by codehz** [tboox/tbox#119]
### 描述问题

https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/coroutine/stackless/prefix.h#L39-L44
此处第二个类型为tb_cpointer_t，意味着它是一个目标不可变的void指针，但是很显然使用场景来看它必须是可变的（虽然c编译器不会把const带到struct上，但是如果目标是一个数字类型，他的问题就来了，没法简单的忽略警告而直接转换为int *

### 期待的结果

去除const限定
```c
typedef tb_void_t       (*tb_lo_coroutine_func_t)(tb_lo_coroutine_ref_t coroutine, tb_pointer_t priv);
```

### 错误信息

（例子来自stackless的自带注释）
```
passing argument 2 of ‘switchtask’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
```

### 相关环境

GCC: 9.2.0

### 其他信息

https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/coroutine/coroutine.h#L46-L47
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/platform/thread.h#L40-L46
这几个也是同样的问题，不过稍微好一点，因为通常你可以本地复制一份存状态。。。但是原则上应该要允许可变

**Comment by codehz** [comment]
下面是搜索 `typedef\.+func_t\.+cpointer_t` 得来的完整列表，部分可能不存在这个问题

https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/coroutine/coroutine.h#L47
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/coroutine/channel.h#L48
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/platform/poller.h#L87
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/memory/fixed_pool.h#L126
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/memory/fixed_pool.h#L129
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/memory/fixed_pool.h#L132
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/network/http.h#L198
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/network/http.h#L210
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/platform/directory.h#L48
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/platform/thread.h#L46
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/container/element.h#L51
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/container/element.h#L61
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/container/element.h#L70
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/container/element.h#L81
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/container/element.h#L98
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/container/element.h#L108
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/container/element.h#L118
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/container/element.h#L139
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/container/element.h#L150
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/container/element.h#L161
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/utils/singleton.h#L114
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/utils/singleton.h#L117
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/utils/singleton.h#L120
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/utils/singleton.h#L123
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/algorithm/walk.h#L40
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/algorithm/rwalk.h#L40
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/platform/timer.h#L44
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/platform/thread_pool.h#L60
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/platform/thread_pool.h#L63
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/platform/thread_pool.h#L66
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/stream/transfer.h#L50
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/coroutine/stackless/prefix.h#L44
https://github.com/tboox/tbox/blob/cc50f173f927b6e9be84383cde4934b8dff6284b/src/tbox/libc/stdio/printf_object.h#L54

**Comment by waruqi** [comment]
设置tb_cpointer_t 主要是为了 tb_lo_coroutine_start 等传入priv参数的，像 常量字符串，还有各种const buffer/struct pointer可以直接传入，省去强制，否则到处强制 代码太乱，看着不顺眼而已。。比如：

```c
tb_lo_coroutine_start(scheduler, func, "hello", tb_null);
tb_byte_t const* buffer = ...;
tb_lo_coroutine_start(scheduler, func, buffer, tb_null);
tb_thread_init(, .. "hello");
```

所以tbox里面只要是priv传入的场景，包括容器，线程等，都统一const void*，就是为了调用的时候省去各种强制过程，看起来更顺眼些。

所以callback里面我就原样透传出来了const void* ，虽然此处还是需要强制，也可能需要强制去掉const，但是毕竟callback里面只需要一处地方强制，但是start()等调用api的priv传入需要到处使用，频率相对较高，相比可以省去不少强制场景。

用户只需要忍受callback那一处地方就好了。

**Comment by waruqi** [comment]
主要就是为了快速简洁的传递常量字符串才这么搞的，insert("xxxx") ，然后为了保证代码风格定义一致，不要太乱，所以所有的priv我都统一tb_cpointer_t了，这块就不用太过于纠结了，个人使用喜好问题。
