### ISSUE TITLE
sqlite3 初始化数据库失败

### ISSUE THREAD

**Issue by jacob1024** [tboox/tbox#123]
嵌入式linux 平台

tbox 加载sqlite3之后，实际运行的时候无法正常初始化

code:
......
tb_database_sql_ref_t database = tb_database_sql_init(“/user/database/test.db”);
if(database)
{
    printf("init database success");
}else
{
    printf("init database fail");
}
......

实际运行输出  init database fail
无法正常初始化,请问下是怎么回事呢？

**Comment by waruqi** [comment]
这个你自己跟下源码好了，可以开启debug编译，里面加点print看下，sqlite3_xxx相关接口的 ret和errno。

**Comment by jacob1024** [comment]
我找到的原因就是路径不对。

我传入的路径是 /user/database/test.db

但是最终在sqlite3_open_v2（path, &sqlite->satabase, SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE, tb_null）中

path 变成了 file:///user/database/test.db  导致无法打开数据库。

我把 file:// 这几个前缀字符去掉就可以了。

这是不是我的用法没对 :)

非常感谢

**Comment by waruqi** [comment]
> path 变成了 file:///user/database/test.db 导致无法打开数据库。

可能是你这的嵌入式linux不支持这种格式路径，这边pc上测试可以访问，不过我dev上刚改进了下，直接透传了 /xxx/xx 文件路径，你可以更新到dev再试试
