### ISSUE TITLE
编译：error: invalid process count(72) for process.waitlist

### ISSUE THREAD

**Issue by llatecomers** [tboox/tbox#125]
> 注：如果是`问题报障`或者`特性请求`，请选择对应issues模板，否则一律不回复。

### 描述问题详情
编译步骤：
1、安装xmake,版本xmake v2.2.9+202001141419
bash <(wget https://raw.githubusercontent.com/xmake-io/xmake/master/scripts/get.sh -O -)
2、下载tbox源码：
git clone https://github.com/tboox/tbox.git
3、编译
cd tbox;xmake
出现error: invalid process count(72) for process.waitlist

系统：16.04.1-Ubuntu SMP Tue Oct 1 14:01:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by waruqi** [comment]
可能是你这linux服务器的cpu core太多了，导致这边xmake默认采用了超过 64 jobs 来并行构建，而xmake内部process进程等待，之前限制了最大64，所以报错了，可以通过如下两种方式解决：

1. xmake -j N 指定构建并行job数，限制到64以内就行
2. 或者更新到dev版本，我改进过了，放宽到了256以内，执行命令更新下：xmake update dev，然后再试

另外，后续xmake相关问题，请到xmake的repo/issues反馈。

**Comment by llatecomers** [comment]
嗯。确实在服务器上面编译可以CPU core过多。按照步骤1解决该问题。
