### ISSUE TITLE
在mac上编译android版本出现问题

### ISSUE THREAD

**Issue by llatecomers** [tboox/tbox#128]
[ 48%]: compiling.release src/tbox/platform/socket.c
error: src/tbox/platform/posix/socket.c:361:34: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    struct sockaddr_storage d = {0};
                                 ^
                                 {}
src/tbox/platform/posix/socket.c:386:34: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    struct sockaddr_storage d = {0};
                                 ^
                                 {}
src/tbox/platform/posix/socket.c:442:34: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    struct sockaddr_storage d = {0};
                                 ^
                                 {}
src/tbox/platform/posix/socket.c:485:34: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    struct sockaddr_storage d = {0};
                                 ^
                                 {}
src/tbox/platform/posix/socket.c:666:34: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]

**Comment by waruqi** [comment]
我修复了，你更新到dev分支试试

**Comment by llatecomers** [comment]
不好意思，之前查看类似issue我把xmake.lua中的set_warnings("all", "error")屏蔽了，后面可以编译通过。后面这边切换到dev分支下还是报同样的错误。
hubinxiongdeMacBook-Pro:tbox hubinxiong$ git branch
  master
* remotes/origin/dev
错误：
[ 48%]: compiling.realease src/tbox/platform/socket.c
error: src/tbox/platform/posix/socket.c:442:34: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    struct sockaddr_storage d = {0};
                                 ^
                                 {}
src/tbox/platform/posix/socket.c:485:34: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    struct sockaddr_storage d = {0};
                                 ^
                                 {}
src/tbox/platform/posix/socket.c:666:34: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    struct sockaddr_storage d = {0};
                                 ^
                                 {}
src/tbox/platform/posix/socket.c:770:34: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]

**Comment by waruqi** [comment]
不可能还有，请确认已经更新到最新dev commit， 4b28e8fba6be227084e03fa91dad5fe5744671af

**Comment by llatecomers** [comment]
看官网上dev的socket.c的源码，你之前确实处理了原先361，386两个位置的错误，但是目前442、485、666、770这几行好像漏掉处理。

**Comment by waruqi** [comment]
我改了，你再试试
