### ISSUE TITLE
怎么编译协程库

### ISSUE THREAD

**Issue by wanggujin** [tboox/tbox#129]
请问，怎么编译coroutine 这个库？

**Comment by waruqi** [comment]
xmake f --coroutine=y

**Comment by wanggujin** [comment]
还是不行，还是链接不到相关函数。
TestSwitch/main.c:17: error: undefined reference to `tb_coroutine_start'  之类的错误。
其实我就在编译demo里面的switch.c

**Comment by wanggujin** [comment]
好了。可以了
