### ISSUE TITLE
tb_check_mode

### ISSUE THREAD

**Issue by wanggujin** [tboox/tbox#130]
[tbox]: init: ..
[tbox]: [error]: libtbox.a has __tb_debug__ but tbox/tbox.h not at tb_check_mode(): 84, src/tbox/tbox.c

这个错误怎么弄？我编译的debug模式的库。

**Comment by waruqi** [comment]
头文件 tbox.config.h 和 .a库 模式不匹配，估计你用的release版本的头文件。。

所以tb_init内部检测没通过。。得一一对应才行

**Comment by wanggujin** [comment]
xmake f --coroutine=y -m debug
xmake install -o /opt/tbox/debug

我这样编译、安装的

**Comment by waruqi** [comment]
追加-c重新检测生成下 tbox.config.h

xmake f --coroutine=y -m debug -c
xmake
xmake install -o /opt/tbox/debug

或者你用xmake package，会自动根据不同平台、arch，调试模式给你归类打包inc/pkg 直接可用，不用install

**Comment by wanggujin** [comment]
一样的问题，tbox.config.h 里根本没有出现debug/DEBUG 的字样。
我是ubuntu 16.04  64位
gcc 5.4

**Comment by waruqi** [comment]
哦 我忘记了 debug库 你得自己加__tb_debug__定义

**Comment by waruqi** [comment]
或者你可以直接用xmake接入 tbox使用，具体有文档 https://tboox.io/#/zh-cn/guide/quickstart
