### ISSUE TITLE
tb_lo_coroutine_wait_sock 无法循环读取socket中的数据

### ISSUE THREAD

**Issue by jococi** [tboox/tbox#131]
### 描述问题详情
通过携程创建的socket client循环读取服务器发送的数据包。但是总是在读取到一个数据后退出了循环。代码如下：

tb_void_t CSocket::tb_client_lo_coroutine_echo(tb_lo_coroutine_ref_t coroutine, tb_cpointer_t priv)
{
    CSocket *s = (CSocket *)priv;
    tb_lo_coroutine_enter(coroutine)
    {
        s->sock = tb_socket_init(TB_SOCKET_TYPE_TCP, TB_IPADDR_FAMILY_IPV4);
        tb_assert_and_check_break(s->sock);
        // trace
        tb_trace_i("connecting %{ipaddr} ..", &s->addr);
        while (!(s->ok = tb_socket_connect(s->sock, &s->addr)))
        {
            // wait it
            tb_lo_coroutine_wait_sock(s->sock, TB_SOCKET_EVENT_CONN, 5000);

            // wait failed?
            if (tb_lo_coroutine_wait_result() <= 0)
                break;
        }
        // connect ok?

        if (s->ok <= 0)
        {
            /* 链接失败 code */
            tb_trace_i("connect err %{ipaddr} ..", &s->addr);
            break;
        }

        // trace
        tb_trace_i("tb_socket_recv  start :%lu ..", s->id);
        tb_byte_t data[1024 * 4];
        //读取头
        while (1)
        {
            // read it
            tb_memset(data, 0, 1024 * 4);
            s->real = tb_socket_recv(s->sock, data, 1024 * 4);
            // has data?
            if (s->real > 0)
            {
                tb_trace_i("tb_socket_recved %s  ..", data);
                tb_buffer_memncat(&s->buffer, data, s->read);
                //s->OnMessage(&s->buffer);
                s->wait = 0;
            }
            else if (!s->real && !s->wait)
            {
                tb_trace_i("tb_lo_coroutine_wait_sock %{ipaddr}  ..", &s->addr);
                tb_lo_coroutine_wait_sock(s->sock, TB_SOCKET_EVENT_RECV, -1);
        
            }
            else
                break;
        }
        tb_trace_i("tb_socket_recved %s  ..", data);
        if (s->sock)
            tb_socket_exit(s->sock);
        s->sock = tb_null;
        tb_trace_i("tb_socket_exit %{ipaddr}  ..", &s->addr);
    }
}

**Comment by waruqi** [comment]
stackless协程 不能用局部变量 具体看下文档 https://tboox.org/cn/2016/12/03/stackless-coroutine/
