### ISSUE TITLE
tb_time_t sizeof() value

### ISSUE THREAD

**Issue by pioneerAlone** [tboox/tbox#138]
// hong and hize
typedef tb_sint64_t                 tb_hong_t;
/// the time type
typedef tb_hong_t                   tb_time_t;
The tb_time_t in tbox occupies 8 bytes, can't it be changed according to the number of platforms?

**Comment by waruqi** [comment]
Do not consider modifying it, tb_time_t is only used for the interface provided by tbox, it will not be directly passed into the system api and libc interface, and there is no need to rely on the definition of the platform

**Comment by pioneerAlone** [comment]
time_t tim = 0;
tim = tb_mktime(&lt);
自己这样试了一下，发现标准的time_t 能够正确接收 tb_time_t的返回值

**Comment by waruqi** [comment]
> time_t tim = 0;
> tim = tb_mktime(&lt);
> 自己这样试了一下，发现标准的time_t 能够正确接收 tb_time_t的返回值

time_t 反而是依赖平台的，有的编译器平台time_t是32bits，你怎么搞直接取址给tb_mktime反而有问题，给tbox接口，就要用tbox提供的type，就是为了解决平台差异性导致的各种问题

tb_time_t tim = 0;
tim = tb_mktime(&lt);

你如果后续还是要用time_t，你取出来再强转不就行了

time_t tim2 = (time_t)tim;
