### ISSUE TITLE
ltimer 应用

### ISSUE THREAD

**Issue by pioneerAlone** [tboox/tbox#139]
写了一个这样的低精度定时器，旨在通过tick、tickCount，来改变定时器的周期，但是反复的调用
tb_ltimer_exit(timer)、 timer = tb_ltimer_init(3, tick, tb_false)、tb_thread_init(tb_null, tb_gps_ltimer_loop, timer, 0）,导致cpu的占用率达到100%，来回几次程序就挂了，内存的使用率很正常，这样的做法可行吗？
tb_int_t tb_ltimer_start(tb_size_t tick,tb_size_t tickCount){

    if(timer)tb_ltimer_exit(timer);
    printf("timer init enter\n");
    timer = tb_ltimer_init(3, tick, tb_false);
    if(timer){
        // the limit and delay
        tb_size_t limit         = tb_ltimer_limit(timer);
        tb_size_t delay         = tb_ltimer_delay(timer);
        printf("limit: %lu, delay: %lu\n", limit, delay);
        gps_task= tb_ltimer_task_init(timer, tickCount * delay, tb_true, tb_gps_timer_task_func, "periodic");
        // init loop
        tb_thread_init(tb_null, tb_gps_ltimer_loop, timer, 0);
    }
    return 0;
}

**Comment by waruqi** [comment]
不知道你要做什么，tb_ltimer_init干嘛来回调，全局维护一个就行了，一个timer，内部可以提交n多timer tasks了，不带你这么玩的。。

**Comment by pioneerAlone** [comment]
想实现GPS周期性校时的周期设置，想改变周期的tick单位，这样delay的值可以相对变小，相当于给一个延时单位，给一个单位计数，以此来改变周期，毕竟定时器给了4个精度，以为可以这样玩，看来想多了

**Comment by waruqi** [comment]
> 想实现GPS周期性校时的周期设置，想改变周期的tick单位，这样delay的值可以相对变小，相当于给一个延时单位，给一个单位计数，以此来改变周期，毕竟定时器给了4个精度，以为可以这样玩，看来想多了

理论上是可以的，但是这样来回创建释放资源，对性能会有影响，创建一个timer，仅仅只是跑一个task就给整个exit了，这也太那个了。。

你要延迟小，那就直接用最小的精度就好了，或者干脆创建四个精度的timer

要么就直接用 tb_timer_init这个是高精度的，用的minheap，没有精度损失。效率也还好了。。
