### ISSUE TITLE
关于“typedef __tb_typeref__(fixed_pool);”用法的疑问？

### ISSUE THREAD

**Issue by tangaoo** [tboox/tbox#141]
跟您请教下“typedef __tb_typeref__(fixed_pool);”相关的问题？
1. 在头文件这样做的目的是啥？按我的理解这样做只是为了让头文件编译通过，因为头文件里面引用了tb_fixed_pool_ref_t。为什么不把结构体声明从.c移动到.h文件中？
2.在.h里面tb_fixed_pool_ref_t只是一个dummy，它是如何转换成真正有效的？我看到对应.c里面有tb_fixed_pool_t结构体类型的定义。

**Comment by waruqi** [comment]
1. 

就是不想暴露 tb_fixed_pool_ref_t 的实际 struct body定义，隐藏到.c 才这么干的。。用户干嘛要知道 tb_fixed_pool_ref_t 的实际定义是啥呢？要篡改里面的members? 需要让用户改状态的，会提供public api给你改，没开放的接口的，就是说明不想让用户随意改。。

tb_fixed_pool_ref_t 对用户而言就是一个 对象的引用，仅此而已，里面的数据怎么定义的 是内部实现的事，用户不需要关心，否则暴露给外面，只会被用户乱用乱改。

2. 

搞成struct { dummy }的 匿名引用，除了隐藏真实定义，而且是强类型的，比起 void*，可以避免用户传错对象 到 其他接口。。

3. 

另外在头文件定义 struct暴露，很容易由于 头文件 和 .a库的版本不匹配（比如用了新版本.h的struct定义，新增了几个member，或者struct layout order全部变了）

但是用了老的.a库，编译时候也许不会报错，但是struct定义在栈上的写入很可能导致程序各种栈溢出或者错乱 引发未定义行为和崩溃。

4. 当然也有少部分我还是开放了struct到.h的，但极少，仅仅用于一些确实需要提供给用户访问和修改struct members的情况。

**Comment by waruqi** [comment]
越多的struct定义暴露到头文件，还会带来更多的类型定义依赖所在的 私有头文件全部开放到 外面。。对外提供给用户的 头文件越多，更容易导致各种编译问题，尤其是 依赖的平台相关的 系统头文件。。

对象的struct尽量隐藏到.c，可以把它依赖的各种私有文件、系统头文件全部隐藏到.c，只对tbox库编译生效，对用户导出的头文件可以不带出来，提高跨平台性和可编译性。

**Comment by tangaoo** [comment]
明白了，感谢耐心回复！
