### ISSUE TITLE
交叉编译问题

### ISSUE THREAD

**Issue by chenfuchen** [tboox/tbox#143]
hello，请教一下，使用如下指令配置：
xmake f -p linux -m debug --sdk=/opt/arm-2014.05/ --xml=y --object=y --coroutine=y
编译时提示如下错误：

error: src/tbox/stream/../prefix/assert.h:255:58: error: size of array '__tb_static_assert__' is negative
 #   define tb_assert_static(x)          do { typedef int __tb_static_assert__[(x)? 1 : -1]; __tb_volatile__ __tb_static_assert__ __a; tb_used_ptr((tb_cpointer_t)(tb_size_t)__a);} while(0)
                                                          ^
src/tbox/stream/../platform/atomic.h:289:5: note: in expansion of macro 'tb_assert_static'
     tb_assert_static(sizeof(tb_atomic_flag_t) == sizeof(tb_atomic32_t));
     ^
src/tbox/stream/../platform/atomic.h: In function 'tb_atomic_flag_test_explicit_generic':
src/tbox/stream/../prefix/assert.h:255:58: error: size of array '__tb_static_assert__' is negative
 #   define tb_assert_static(x)          do { typedef int __tb_static_assert__[(x)? 1 : -1]; __tb_volatile__ __tb_static_assert__ __a; tb_used_ptr((tb_cpointer_t)(tb_size_t)__a);} while(0)
                                                          ^
src/tbox/stream/../platform/atomic.h:298:5: note: in expansion of macro 'tb_assert_static'
     tb_assert_static(sizeof(tb_atomic_flag_t) == sizeof(tb_atomic32_t));
     ^
src/tbox/stream/../platform/atomic.h: In function 'tb_atomic_flag_clear_explicit_generic':
src/tbox/stream/../prefix/assert.h:255:58: error: size of array '__tb_static_assert__' is negative
 #   define tb_assert_static(x)          do { typedef int __tb_static_assert__[(x)? 1 : -1]; __tb_volatile__ __tb_static_assert__ __a; tb_used_ptr((tb_cpointer_t)(tb_size_t)__a);} while(0)

也就是断言sizeof(tb_atomic_flag_t) == sizeof(tb_atomic32_t)失败，请教一下如何解决。

**Comment by waruqi** [comment]
你拉下dev分支代码再试试呢

**Comment by chenfuchen** [comment]
编译通过，谢谢。



---原始邮件---
发件人: "ruki"<notifications@github.com&gt;
发送时间: 2020年7月14日(周二) 晚上10:29
收件人: "tboox/tbox"<tbox@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"chenfuchen"<1311093196@qq.com&gt;;
主题: Re: [tboox/tbox] 交叉编译问题 (#143)




 
你拉下dev分支代码再试试呢
