### ISSUE TITLE
请问在高精度定时器中如何重置定时任务

### ISSUE THREAD

**Issue by jacob1024** [tboox/tbox#146]
我想要实现如下的目的:

启动一个定时任务 task_a ， 目的是检测数据是否中断, 使用 tb_timer_task_init
在10秒之内, 如果检测到数据到达, 那么延迟触发定时任务task_a 。
如果数据一直有, 那么永远也不触发定时任务。
如果数据中断， 那么10秒后触发定时任务。

意思是在定时任务没有被触发之前重置任务, 但是好像没有相关的接口。
请问有什么好的办法，多谢

**Comment by waruqi** [comment]
用tb_timer_task_kill去取消还没被触发的timer task不行么

**Comment by jacob1024** [comment]
demo代码

static tb_void_t tb_demo_timer_task_func(tb_bool_t killed, tb_cpointer_t priv)
{
    // get the time
    tb_timeval_t tv = {0};
    if (tb_gettimeofday(&tv, tb_null))
    {
        // trace
        tb_trace_i("task[%s]: %lld ms, killed: %d", (tb_char_t const*)priv, killed);
    }
}

tb_timer_task_ref_t one ；
one = tb_timer_task_init(tb_timer(), 10000, tb_false, tb_demo_timer_task_func, "111111111");     --  系统时间00：00

// do something
sleep(5);                                                                                   -- 系统时间 00：05 

// 重置定时任务
if (one) tb_timer_task_kill(tb_timer(), one);
one = tb_timer_task_init(tb_timer(), 10000, tb_false, tb_demo_timer_task_func, "222222222");

---------------------------------------------------------------------------------------------------------


实际输出：
task[11111111]: killed: 1     -- -- 系统时间 00：10 
task[22222222]: killed: 0     -- -- 系统时间 00：10  

期望输出：
task[11111111]: killed: 1     -- -- 系统时间 00：05
task[22222222]: killed: 0     -- -- 系统时间 00：15 

实际上 11111111，222222222 这两个任务同时执行了；

**Comment by waruqi** [comment]
可以了，你更新到 dev 分支版本再试试。

另外获取时间 直接用 tb_mclock() 就好了，没必要用 tb_gettimeofday， 而且你的 代码 tv 都没 print 传参，下回贴代码贴完整点。

sleep 也有内置的 tb_sleep，还有你 kill 完，都没去 exit 这个 task ，又去 init 了一个新的，会有内存泄漏。

**Comment by jacob1024** [comment]
谢谢回复， 代码是下班后临时写的 ：）
已经可以了 。

**Comment by jacob1024** [comment]
谢谢回复， 代码是下班后临时写的 ：）
已经可以了 。
