### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by jococi** [tboox/tbox#147]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题
新建的动态库项目添加了tbox 1.6.5，xmake下载完成后无法编译tbox。

### 错误信息
> Executing task: xmake f -p windows -a x86 -m release -o "d:\WorkPlace\git.dayuan.com\chuanma\htobx/build" <

The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command xmake f -p windows -a x86 -m release -o "d:\WorkPlace\git.dayuan.com\chuanma\htobx/build"" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

> Executing task: xmake -w <

checking for the Microsoft Visual Studio (x86) version ... 2017
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> tbox v1.6.5
please input: y (y/n)
n
error: packages(tbox): must be installed!
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command xmake -w" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

> Executing task: xmake f -p windows -a x86 -m debug -o "d:\WorkPlace\git.dayuan.com\chuanma\htobx/build" <

checking for the Microsoft Visual Studio (x86) version ... 2017
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> tbox v1.6.5
please input: y (y/n)
y
  => install tbox v1.6.5 .. failed
if you want to get verbose errors, please see:
  -> C:\Users\Administrator\AppData\Local\.xmake\cache\packages\2008\t\tbox\v1.6.5\installdir.failed\logs\install.txt
error: install failed!
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command xmake f -p windows -a x86 -m debug -o "d:\WorkPlace\git.dayuan.com\chuanma\htobx/build"" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

### 相关环境

win10，vs2017，xmake2.3.6

### 其他信息

[38;5;2m        --mingw=MINGW                  [0m    [0mThe MingW SDK Directory[0m[0m
[38;5;2m[0m
[38;5;2m        --vs=VS                        [0m    [0mThe Microsoft Visual Studio[0m[0m (default: [1mauto[0m)[0m[0m
[38;5;2m                                       [0m    [0m  e.g. --vs=2017[0m[0m
[38;5;2m        --vs_toolset=VS_TOOLSET        [0m    [0mThe Microsoft Visual Studio Toolset Version[0m[0m
[38;5;2m                                       [0m    [0m  e.g. --vs_toolset=14.0[0m[0m
[38;5;2m        --vs_sdkver=VS_SDKVER          [0m    [0mThe Windows SDK Version of Visual Studio[0m[0m
[38;5;2m                                       [0m    [0m  e.g. --vs_sdkver=10.0.15063.0[0m[0m
[38;5;2m[0m
[38;5;2m        --wdk=WDK                      [0m    [0mThe WDK Directory[0m[0m (default: [1mauto[0m)[0m[0m
[38;5;2m        --wdk_sdkver=WDK_SDKVER        [0m    [0mThe WDK Version[0m[0m (default: [1mauto[0m)[0m[0m
[38;5;2m        --wdk_winver=WDK_WINVER        [0m    [0mThe WDK Windows Version[0m[0m (default: [1mauto[0m)[0m[0m
[38;5;2m                                       [0m        - win10[|_rs3][0m
[38;5;2m                                       [0m        - win81[0m
[38;5;2m                                       [0m        - win8[0m
[38;5;2m                                       [0m        - win7[|_sp1|_sp2|_sp3][0m
[38;5;2m[0m
[38;5;2m        --debugger=DEBUGGER            [0m    [0mThe Debugger[0m[0m (default: [1mauto[0m)[0m[0m
[38;5;2m        --ccache=[y|n]                 [0m    [0mEnable or disable the c/c++ compiler cache.[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --trybuild=TRYBUILD            [0m    [0mEnable try-build mode and set the third-party buildsystem tool.[0m[0m
[38;5;2m                                       [0m    [0me.g.[0m[0m
[38;5;2m                                       [0m    [0m    - xmake f --trybuild=auto; xmake[0m[0m
[38;5;2m                                       [0m    [0m    - xmake f --trybuild=autotools -p android --ndk=xxx; xmake[0m[0m
[38;5;2m                                       [0m    [0m[0m[0m
[38;5;2m                                       [0m    [0mthe third-party buildsystems:[0m[0m
[38;5;2m                                       [0m        - auto[0m
[38;5;2m                                       [0m        - make[0m
[38;5;2m                                       [0m        - autotools[0m
[38;5;2m                                       [0m        - cmake[0m
[38;5;2m                                       [0m        - scons[0m
[38;5;2m                                       [0m        - meson[0m
[38;5;2m                                       [0m        - bazel[0m
[38;5;2m                                       [0m        - ninja[0m
[38;5;2m                                       [0m        - msbuild[0m
[38;5;2m                                       [0m        - xcodebuild[0m
[38;5;2m                                       [0m        - ndkbuild[0m
[38;5;2m        --tryconfigs=TRYCONFIGS        [0m    [0mSet the extra configurations of the third-party buildsystem for the try-build mode.[0m[0m
[38;5;2m                                       [0m    [0me.g.[0m[0m
[38;5;2m                                       [0m    [0m    - xmake f --trybuild=autotools --tryconfigs='--enable-shared=no'[0m[0m
[38;5;2m    -o BUILDIR, --buildir=BUILDIR      [0m    [0mSet the build directory.[0m[0m (default: [1mbuild[0m)[0m[0m
[38;5;2m[0m
[38;5;2m          target                       [0m    [0mConfigure for the given target.[0m[0m
[0m[1;38;5;1;1merror: [0minvalid argument: --cxxflags=[0m
[0m[1;38;5;3;1mwarning: [38;5;3;1mifelse(a, b, c) is deprecated, please uses (a and b or c) instead of it[0m

**Comment by waruqi** [comment]
看着眼花，能否给个 plain text。。去掉color code 。。或者直接发下 C:\Users\Administrator\AppData\Local.xmake\cache\packages\2008\t\tbox\v1.6.5\installdir.failed\logs\install.txt

**Comment by jococi** [comment]
下载地址[https://share.weiyun.com/Tn1BX4bs](url)

**Comment by jococi** [comment]
[0m[1mxmake v2.3.6+202007310450, A cross-platform build utility based on Lua[0m[0m
[0mCopyright (C) 2015-2020 Ruki Wang, [4mtboox.org[0m, [4mxmake.io[0m[0m
[0m[38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m_[38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m 
[38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m_[38;5;41m_[38;5;41m [38;5;41m [38;5;41m_[38;5;41m_[38;5;41m_[38;5;41m [38;5;42m_[38;5;42m_[38;5;42m [38;5;42m [38;5;42m_[38;5;42m_[38;5;42m [38;5;42m [38;5;42m_[38;5;42m_[38;5;42m [38;5;42m_[38;5;42m|[38;5;42m [38;5;42m|[38;5;42m [38;5;42m_[38;5;42m_[38;5;42m_[38;5;42m_[38;5;42m_[38;5;42m_[38;5;42m 
[38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m\[38;5;41m [38;5;41m\[38;5;41m/[38;5;41m [38;5;41m/[38;5;41m [38;5;41m|[38;5;42m [38;5;42m [38;5;42m\[38;5;42m/[38;5;42m [38;5;42m [38;5;42m|[38;5;42m/[38;5;42m [38;5;42m_[38;5;42m [38;5;42m [38;5;42m|[38;5;42m [38;5;42m|[38;5;42m/[38;5;42m [38;5;42m/[38;5;42m [38;5;42m_[38;5;42m_[38;5;42m [38;5;42m\
[38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m>[38;5;41m [38;5;41m [38;5;41m<[38;5;41m [38;5;41m [38;5;41m|[38;5;42m [38;5;42m\[38;5;42m_[38;5;42m_[38;5;42m/[38;5;42m [38;5;42m|[38;5;42m [38;5;42m/[38;5;42m_[38;5;42m|[38;5;42m [38;5;42m|[38;5;42m [38;5;42m [38;5;42m [38;5;42m<[38;5;42m [38;5;42m [38;5;42m_[38;5;42m_[38;5;42m_[38;5;42m/
[38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m/[38;5;41m_[38;5;41m/[38;5;41m\[38;5;41m_[38;5;41m\[38;5;41m_[38;5;41m|[38;5;42m_[38;5;42m|[38;5;42m [38;5;42m [38;5;42m|[38;5;42m_[38;5;42m|[38;5;42m\[38;5;42m_[38;5;42m_[38;5;42m [38;5;42m\[38;5;42m|[38;5;42m_[38;5;42m|[38;5;42m\[38;5;42m_[38;5;42m\[38;5;42m_[38;5;42m_[38;5;42m_[38;5;42m_[38;5;42m|[38;5;42m 
[38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;41m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42m [38;5;42mb[38;5;42my[38;5;42m [38;5;42mr[38;5;42mu[38;5;42mk[38;5;42mi[38;5;42m,[38;5;42m [38;5;42mt[38;5;42mb[38;5;42mo[38;5;42mo[38;5;42mx[38;5;42m.[38;5;42mo[38;5;42mr[38;5;43mg
[38;5;41m [38;5;41m [38;5;41m [38;5;41m [0m
[0m    ??  [1mManual[0m: [4mhttps://xmake.io/#/getting_started[0m
    ??  [1mDonate[0m: [4mhttps://xmake.io/#/sponsor[0m
    [0m

[0m[1mUsage: $[0;38;5;6mxmake config|f [options] [target][0m[0m

[0mConfigure the project.[0m
[38;5;2m[0m
[38;5;2m[0;1mCommon options:[0m
[38;5;2m    -q, --quiet                        [0m    [0mQuiet operation.[0m[0m
[38;5;2m    -y, --yes                          [0m    [0mInput yes by default if need user confirm.[0m[0m
[38;5;2m        --confirm=CONFIRM              [0m    [0mInput the given result if need user confirm.[0m[0m
[38;5;2m                                       [0m        - yes[0m
[38;5;2m                                       [0m        - no[0m
[38;5;2m                                       [0m        - def[0m
[38;5;2m    -v, --verbose                      [0m    [0mPrint lots of verbose information for users.[0m[0m
[38;5;2m        --root                         [0m    [0mAllow to run xmake as root.[0m[0m
[38;5;2m    -D, --diagnosis                    [0m    [0mPrint lots of diagnosis information (backtrace, check info ..) only for developers.[0m[0m
[38;5;2m                                       [0m    [0mAnd we can append -v to get more whole information.[0m[0m
[38;5;2m                                       [0m    [0m    e.g. $ xmake -vD[0m[0m
[38;5;2m        --profile                      [0m    [0mPrint performance data only for developers.[0m[0m
[38;5;2m        --version                      [0m    [0mPrint the version number and exit.[0m[0m
[38;5;2m    -h, --help                         [0m    [0mPrint this help message and exit.[0m[0m
[38;5;2m[0m
[38;5;2m    -F FILE, --file=FILE               [0m    [0mRead a given xmake.lua file.[0m[0m
[38;5;2m    -P PROJECT, --project=PROJECT      [0m    [0mChange to the given project directory.[0m[0m
[38;5;2m                                       [0m    [0mSearch priority:[0m[0m
[38;5;2m                                       [0m    [0m    1. The Given Command Argument[0m[0m
[38;5;2m                                       [0m    [0m    2. The Envirnoment Variable: XMAKE_PROJECT_DIR[0m[0m
[38;5;2m                                       [0m    [0m    3. The Current Directory[0m[0m
[38;5;2m[0m
[38;5;2m[0;1mCommand options (config):[0m
[38;5;2m    -c, --clean                        [0m    [0mClean the cached configure and configure all again.[0m[0m
[38;5;2m        --menu                         [0m    [0mConfigure project with a menu-driven user interface.[0m[0m
[38;5;2m[0m
[38;5;2m    -p PLAT, --plat=PLAT               [0m    [0mCompile for the given platform.[0m[0m (default: [1mwindows[0m)[0m[0m
[38;5;2m                                       [0m        - android[0m
[38;5;2m                                       [0m        - bsd[0m
[38;5;2m                                       [0m        - cross[0m
[38;5;2m                                       [0m        - cygwin[0m
[38;5;2m                                       [0m        - iphoneos[0m
[38;5;2m                                       [0m        - linux[0m
[38;5;2m                                       [0m        - macosx[0m
[38;5;2m                                       [0m        - mingw[0m
[38;5;2m                                       [0m        - msys[0m
[38;5;2m                                       [0m        - watchos[0m
[38;5;2m                                       [0m        - windows[0m
[38;5;2m    -a ARCH, --arch=ARCH               [0m    [0mCompile for the given architecture.[0m[0m (default: [1mauto[0m)[0m[0m
[38;5;2m                                       [0m        - android: armeabi armeabi-v7a arm64-v8a x86 x86_64 mips mip64[0m
[38;5;2m                                       [0m        - bsd: i386 x86_64[0m
[38;5;2m                                       [0m        - cross: i386 x86_64 armv7 armv7s arm64-v8a mips mips64[0m
[38;5;2m                                       [0m        - cygwin: i386 x86_64[0m
[38;5;2m                                       [0m        - iphoneos: arm64 armv7 armv7s i386 x86_64[0m
[38;5;2m                                       [0m        - linux: i386 x86_64 armv7 armv7s arm64-v8a mips mips64[0m
[38;5;2m                                       [0m        - macosx: i386 x86_64[0m
[38;5;2m                                       [0m        - mingw: i386 x86_64[0m
[38;5;2m                                       [0m        - msys: i386 x86_64[0m
[38;5;2m                                       [0m        - watchos: armv7k i386[0m
[38;5;2m                                       [0m        - windows: x86 x64[0m
[38;5;2m    -m MODE, --mode=MODE               [0m    [0mCompile for the given mode.[0m[0m (default: [1mrelease[0m)[0m[0m
[38;5;2m                                       [0m        - debug[0m
[38;5;2m                                       [0m        - release[0m
[38;5;2m                                       [0m        - ... (custom)[0m
[38;5;2m    -k KIND, --kind=KIND               [0m    [0mCompile for the given target kind.[0m[0m (default: [1mstatic[0m)[0m[0m
[38;5;2m                                       [0m        - static[0m
[38;5;2m                                       [0m        - shared[0m
[38;5;2m                                       [0m        - binary[0m
[38;5;2m        --host=HOST                    [0m    [0mThe Current Host Environment.[0m[0m (default: [1mwindows[0m)[0m[0m
[38;5;2m[0m
[38;5;2m        --require=REQUIRE              [0m    [0mRequire all dependent packages?[0m[0m
[38;5;2m                                       [0m        - y: force to enable[0m
[38;5;2m                                       [0m        - n: disable[0m
[38;5;2m        --pkg_searchdirs=PKG_SEARCHDIRS[0m    [0mThe search directories of the remote package.[0m[0m
[38;5;2m                                       [0m    [0m    e.g.[0m[0m
[38;5;2m                                       [0m    [0m    - xmake f --pkg_searchdirs=/dir1;/dir2[0m[0m
[38;5;2m[0m
[38;5;2m        --float=[y|n]                  [0m    [0mEnable or disable the float type[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --demo=[y|n]                   [0m    [0mEnable or disable the demo module[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --info=[y|n]                   [0m    [0mEnable or disable to get some info, .e.g version ..[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --exception=[y|n]              [0m    [0mEnable or disable the exception.[0m[0m
[38;5;2m        --deprecated=[y|n]             [0m    [0mEnable or disable the deprecated interfaces.[0m[0m
[38;5;2m        --micro=[y|n]                  [0m    [0mCompile micro core library for the embed system.[0m[0m
[38;5;2m        --force-utf8=[y|n]             [0m    [0mForcely regard all tb_char* as utf-8.[0m[0m
[38;5;2m        --small=[y|n]                  [0m    [0mEnable the small compile mode and disable all modules.[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m[0m
[38;5;2m        --object=[y|n]                 [0m    [0mThe object module[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --database=[y|n]               [0m    [0mThe database module[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --coroutine=[y|n]              [0m    [0mThe coroutine module[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --zip=[y|n]                    [0m    [0mThe zip module[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --xml=[y|n]                    [0m    [0mThe xml module[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --charset=[y|n]                [0m    [0mThe charset module[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --hash=[y|n]                   [0m    [0mThe hash module[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --regex=[y|n]                  [0m    [0mThe regex module[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m[0m
[38;5;2m        --polarssl=[y|n]               [0m    [0mEnable the polarssl package.[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --pcre=[y|n]                   [0m    [0mEnable the pcre package.[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --pcre2=[y|n]                  [0m    [0mEnable the pcre2 package.[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --openssl=[y|n]                [0m    [0mEnable the openssl package.[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --zlib=[y|n]                   [0m    [0mEnable the zlib package.[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --mysql=[y|n]                  [0m    [0mEnable the mysql package.[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --sqlite3=[y|n]                [0m    [0mEnable the sqlite3 package.[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --mbedtls=[y|n]                [0m    [0mEnable the mbedtls package.[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m[0m
[38;5;2m        --cross=CROSS                  [0m    [0mThe Cross Toolchains Prefix[0m[0m
[38;5;2m                                       [0m    [0me.g.[0m[0m
[38;5;2m                                       [0m    [0m    - i386-mingw32-[0m[0m
[38;5;2m                                       [0m    [0m    - arm-linux-androideabi-[0m[0m
[38;5;2m        --bin=BIN                      [0m    [0mThe Cross Toolchains Bin Directory[0m[0m
[38;5;2m                                       [0m    [0me.g.[0m[0m
[38;5;2m                                       [0m    [0m    - sdk/bin (/arm-linux-gcc ..)[0m[0m
[38;5;2m        --sdk=SDK                      [0m    [0mThe Cross SDK Directory[0m[0m
[38;5;2m                                       [0m    [0me.g.[0m[0m
[38;5;2m                                       [0m    [0m    - sdk/bin[0m[0m
[38;5;2m                                       [0m    [0m    - sdk/lib[0m[0m
[38;5;2m                                       [0m    [0m    - sdk/include[0m[0m
[38;5;2m        --toolchain=TOOLCHAIN          [0m    [0mThe Toolchain Name[0m[0m
[38;5;2m                                       [0m    [0me.g. [0m[0m
[38;5;2m                                       [0m    [0m    - xmake f --toolchain=clang[0m[0m
[38;5;2m                                       [0m    [0m    - xmake f --toolchain=[cross|llvm|sdcc ..] --sdk=/xxx[0m[0m
[38;5;2m                                       [0m    [0m    - run `xmake show -l toolchains` to get all toolchains[0m[0m
[38;5;2m[0m
[38;5;2m        --cc=CC                        [0m    [0mThe C Compiler[0m[0m
[38;5;2m        --cxx=CXX                      [0m    [0mThe C++ Compiler[0m[0m
[38;5;2m        --cpp=CPP                      [0m    [0mThe C Preprocessor[0m[0m
[38;5;2m[0m
[38;5;2m        --ld=LD                        [0m    [0mThe Linker[0m[0m
[38;5;2m        --ar=AR                        [0m    [0mThe Static Library Linker[0m[0m
[38;5;2m        --sh=SH                        [0m    [0mThe Shared Library Linker[0m[0m
[38;5;2m        --ranlib=RANLIB                [0m    [0mThe Static Library Index Generator[0m[0m
[38;5;2m[0m
[38;5;2m        --cflags=CFLAGS                [0m    [0mThe C Compiler Flags[0m[0m
[38;5;2m        --cxflags=CXFLAGS              [0m    [0mThe C/C++ compiler Flags[0m[0m
[38;5;2m        --cxxflags=CXXFLAGS            [0m    [0mThe C++ Compiler Flags[0m[0m
[38;5;2m[0m
[38;5;2m        --ldflags=LDFLAGS              [0m    [0mThe Binary Linker Flags[0m[0m
[38;5;2m        --arflags=ARFLAGS              [0m    [0mThe Static Library Linker Flags[0m[0m
[38;5;2m        --shflags=SHFLAGS              [0m    [0mThe Shared Library Linker Flags[0m[0m
[38;5;2m[0m
[38;5;2m        --links=LINKS                  [0m    [0mThe Link Libraries[0m[0m
[38;5;2m        --syslinks=SYSLINKS            [0m    [0mThe System Link Libraries[0m[0m
[38;5;2m        --linkdirs=LINKDIRS            [0m    [0mThe Link Search Directories[0m[0m
[38;5;2m        --includedirs=INCLUDEDIRS      [0m    [0mThe Include Search Directories[0m[0m
[38;5;2m        --frameworks=FRAMEWORKS        [0m    [0mThe Frameworks[0m[0m
[38;5;2m        --frameworkdirs=FRAMEWORKDIRS  [0m    [0mThe Frameworks Search Directories[0m[0m
[38;5;2m[0m
[38;5;2m        --rc=RC                        [0m    [0mThe Rust Compiler[0m[0m
[38;5;2m[0m
[38;5;2m        --rcld=RCLD                    [0m    [0mThe Rust Linker[0m[0m
[38;5;2m        --rcar=RCAR                    [0m    [0mThe Rust Static Library Archiver[0m[0m
[38;5;2m        --rcsh=RCSH                    [0m    [0mThe Rust Shared Library Linker[0m[0m
[38;5;2m[0m
[38;5;2m        --fc=FC                        [0m    [0mThe Fortran Compiler[0m[0m
[38;5;2m[0m
[38;5;2m        --fcld=FCLD                    [0m    [0mThe Fortran Linker[0m[0m
[38;5;2m        --fcsh=FCSH                    [0m    [0mThe Fortran Shared Library Linker[0m[0m
[38;5;2m[0m
[38;5;2m        --mm=MM                        [0m    [0mThe Objc Compiler[0m[0m
[38;5;2m        --mxx=MXX                      [0m    [0mThe Objc++ Compiler[0m[0m
[38;5;2m[0m
[38;5;2m        --mflags=MFLAGS                [0m    [0mThe Objc Compiler Flags[0m[0m
[38;5;2m        --mxflags=MXFLAGS              [0m    [0mThe Objc/c++ Compiler Flags[0m[0m
[38;5;2m        --mxxflags=MXXFLAGS            [0m    [0mThe Objc++ Compiler Flags[0m[0m
[38;5;2m[0m
[38;5;2m        --go=GO                        [0m    [0mThe Golang Compiler[0m[0m
[38;5;2m[0m
[38;5;2m        --gcld=GCLD                    [0m    [0mThe Golang Linker[0m[0m
[38;5;2m        --go-ar=GO-AR                  [0m    [0mThe Golang Static Library Linker[0m[0m
[38;5;2m[0m
[38;5;2m        --sc=SC                        [0m    [0mThe Swift Compiler[0m[0m
[38;5;2m[0m
[38;5;2m        --scld=SCLD                    [0m    [0mThe Swift Linker[0m[0m
[38;5;2m        --scsh=SCSH                    [0m    [0mThe Swift Shared Library Linker[0m[0m
[38;5;2m[0m
[38;5;2m        --zc=ZC                        [0m    [0mThe Zig Compiler[0m[0m
[38;5;2m[0m
[38;5;2m        --zcld=ZCLD                    [0m    [0mThe Zig Linker[0m[0m
[38;5;2m        --zcar=ZCAR                    [0m    [0mThe Zig Static Library Archiver[0m[0m
[38;5;2m        --zcsh=ZCSH                    [0m    [0mThe Zig Shared Library Linker[0m[0m
[38;5;2m[0m
[38;5;2m        --dc=DC                        [0m    [0mThe Dlang Compiler[0m[0m
[38;5;2m[0m
[38;5;2m        --dcld=DCLD                    [0m    [0mThe Dlang Linker[0m[0m
[38;5;2m        --dcar=DCAR                    [0m    [0mThe Dlang Static Library Archiver[0m[0m
[38;5;2m        --dcsh=DCSH                    [0m    [0mThe Dlang Shared Library Linker[0m[0m
[38;5;2m[0m
[38;5;2m        --as=AS                        [0m    [0mThe Assembler[0m[0m
[38;5;2m[0m
[38;5;2m        --asflags=ASFLAGS              [0m    [0mThe Assembler Flags[0m[0m
[38;5;2m[0m
[38;5;2m        --cu=CU                        [0m    [0mThe Cuda Compiler[0m[0m
[38;5;2m        --cu-ccbin=CU-CCBIN            [0m    [0mThe Cuda Host C++ Compiler[0m[0m
[38;5;2m        --culd=CULD                    [0m    [0mThe Cuda Linker[0m[0m
[38;5;2m[0m
[38;5;2m        --cuflags=CUFLAGS              [0m    [0mThe Cuda Compiler Flags[0m[0m
[38;5;2m        --culdflags=CULDFLAGS          [0m    [0mThe Cuda Linker Flags[0m[0m
[38;5;2m[0m
[38;5;2m        --mrc=MRC                      [0m    [0mThe Microsoft Resource Compiler[0m[0m
[38;5;2m[0m
[38;5;2m        --mrcflags=MRCFLAGS            [0m    [0mThe Microsoft Resource Flags[0m[0m
[38;5;2m[0m
[38;5;2m        --ndk=NDK                      [0m    [0mThe NDK Directory[0m[0m
[38;5;2m        --ndk_sdkver=NDK_SDKVER        [0m    [0mThe SDK Version for NDK[0m[0m (default: [1mauto[0m)[0m[0m
[38;5;2m        --android_sdk=ANDROID_SDK      [0m    [0mThe Android SDK Directory[0m[0m
[38;5;2m        --build_toolver=BUILD_TOOLVER  [0m    [0mThe Build Tool Version of Android SDK[0m[0m
[38;5;2m        --ndk_stdcxx=[y|n]             [0m    [0mUse stdc++ library for NDK[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --ndk_cxxstl=NDK_CXXSTL        [0m    [0mThe stdc++ stl library for NDK[0m[0m
[38;5;2m                                       [0m    [0m    - c++_static[0m[0m
[38;5;2m                                       [0m    [0m    - c++_shared[0m[0m
[38;5;2m                                       [0m    [0m    - gnustl_static[0m[0m
[38;5;2m                                       [0m    [0m    - gnustl_shared[0m[0m
[38;5;2m                                       [0m    [0m    - stlport_shared[0m[0m
[38;5;2m                                       [0m    [0m    - stlport_static[0m[0m
[38;5;2m[0m
[38;5;2m        --cuda=CUDA                    [0m    [0mThe Cuda SDK Directory[0m[0m (default: [1mauto[0m)[0m[0m
[38;5;2m[0m
[38;5;2m        --qt=QT                        [0m    [0mThe Qt SDK Directory[0m[0m (default: [1mauto[0m)[0m[0m
[38;5;2m        --qt_sdkver=QT_SDKVER          [0m    [0mThe Qt SDK Version[0m[0m (default: [1mauto[0m)[0m[0m
[38;5;2m[0m
[38;5;2m        --vcpkg=VCPKG                  [0m    [0mThe Vcpkg Directory[0m[0m (default: [1mauto[0m)[0m[0m
[38;5;2m[0m
[38;5;2m        --mingw=MINGW                  [0m    [0mThe MingW SDK Directory[0m[0m
[38;5;2m[0m
[38;5;2m        --vs=VS                        [0m    [0mThe Microsoft Visual Studio[0m[0m (default: [1mauto[0m)[0m[0m
[38;5;2m                                       [0m    [0m  e.g. --vs=2017[0m[0m
[38;5;2m        --vs_toolset=VS_TOOLSET        [0m    [0mThe Microsoft Visual Studio Toolset Version[0m[0m
[38;5;2m                                       [0m    [0m  e.g. --vs_toolset=14.0[0m[0m
[38;5;2m        --vs_sdkver=VS_SDKVER          [0m    [0mThe Windows SDK Version of Visual Studio[0m[0m
[38;5;2m                                       [0m    [0m  e.g. --vs_sdkver=10.0.15063.0[0m[0m
[38;5;2m[0m
[38;5;2m        --wdk=WDK                      [0m    [0mThe WDK Directory[0m[0m (default: [1mauto[0m)[0m[0m
[38;5;2m        --wdk_sdkver=WDK_SDKVER        [0m    [0mThe WDK Version[0m[0m (default: [1mauto[0m)[0m[0m
[38;5;2m        --wdk_winver=WDK_WINVER        [0m    [0mThe WDK Windows Version[0m[0m (default: [1mauto[0m)[0m[0m
[38;5;2m                                       [0m        - win10[|_rs3][0m
[38;5;2m                                       [0m        - win81[0m
[38;5;2m                                       [0m        - win8[0m
[38;5;2m                                       [0m        - win7[|_sp1|_sp2|_sp3][0m
[38;5;2m[0m
[38;5;2m        --debugger=DEBUGGER            [0m    [0mThe Debugger[0m[0m (default: [1mauto[0m)[0m[0m
[38;5;2m        --ccache=[y|n]                 [0m    [0mEnable or disable the c/c++ compiler cache.[0m[0m (default: [1my[0m)[0m[0m
[38;5;2m        --trybuild=TRYBUILD            [0m    [0mEnable try-build mode and set the third-party buildsystem tool.[0m[0m
[38;5;2m                                       [0m    [0me.g.[0m[0m
[38;5;2m                                       [0m    [0m    - xmake f --trybuild=auto; xmake[0m[0m
[38;5;2m                                       [0m    [0m    - xmake f --trybuild=autotools -p android --ndk=xxx; xmake[0m[0m
[38;5;2m                                       [0m    [0m[0m[0m
[38;5;2m                                       [0m    [0mthe third-party buildsystems:[0m[0m
[38;5;2m                                       [0m        - auto[0m
[38;5;2m                                       [0m        - make[0m
[38;5;2m                                       [0m        - autotools[0m
[38;5;2m                                       [0m        - cmake[0m
[38;5;2m                                       [0m        - scons[0m
[38;5;2m                                       [0m        - meson[0m
[38;5;2m                                       [0m        - bazel[0m
[38;5;2m                                       [0m        - ninja[0m
[38;5;2m                                       [0m        - msbuild[0m
[38;5;2m                                       [0m        - xcodebuild[0m
[38;5;2m                                       [0m        - ndkbuild[0m
[38;5;2m        --tryconfigs=TRYCONFIGS        [0m    [0mSet the extra configurations of the third-party buildsystem for the try-build mode.[0m[0m
[38;5;2m                                       [0m    [0me.g.[0m[0m
[38;5;2m                                       [0m    [0m    - xmake f --trybuild=autotools --tryconfigs='--enable-shared=no'[0m[0m
[38;5;2m    -o BUILDIR, --buildir=BUILDIR      [0m    [0mSet the build directory.[0m[0m (default: [1mbuild[0m)[0m[0m
[38;5;2m[0m
[38;5;2m          target                       [0m    [0mConfigure for the given target.[0m[0m
[0m[1;38;5;1;1merror: [0minvalid argument: --cxxflags=[0m
[0m[1;38;5;3;1mwarning: [38;5;3;1mifelse(a, b, c) is deprecated, please uses (a and b or c) instead of it[0m

**Comment by waruqi** [comment]
直接GitHub issues不就能传附件么。。

你执行下 `xmake f -cvD` 给我看下完整输出呢？

**Comment by jococi** [comment]
[debug.txt](https://github.com/tboox/tbox/files/5068224/debug.txt)

**Comment by waruqi** [comment]
收到 我回头看下

**Comment by waruqi** [comment]
我更新了下，你再试试 dev 分支版本， xmake update -s dev 更新下。

另外你这是不是 add_requires("tbox", {configs = {cxflags= "-fPIC"}})  里面加了 -fPIC 。。这个去掉。。msvc 不支持这个 flags

**Comment by jococi** [comment]
可以了。厉害
