### ISSUE TITLE
没有理解singleton模块作用

### ISSUE THREAD

**Issue by tangaoo** [tboox/tbox#148]
您的库非常棒！
在读源码时，没有理解singleton模块作用，能否麻烦您简单解释一下呢？

**Comment by waruqi** [comment]
就是多线程安全地创建一个单例全局对象，并确保其 init & exit 仅有一次并且线程安全，init 会在首次访问时候自动执行，tb_exit 退出整个库时候，也会自动调用 exit 销毁对象。

而用户只需要通过 tb_xxx()-> 去直接全局访问这个对象就行了，用户不用额外调用 init 和 exit 去创建对象实例。

当然，对象内部的数据访问需要自己通过 lock/mutex 去维护多线程安全。

**Comment by tangaoo** [comment]
明白了，感谢
