### ISSUE TITLE
静态内存分配器（tb_static_allocator）粒度问题

### ISSUE THREAD

**Issue by tangaoo** [tboox/tbox#149]
您的库非常棒。

我的应用平台是嵌入式环境，根据您的readme介绍选择了静态内存分配器（tb_static_allocator）。在阅读源码时发现tb_static_allocator是调用static_large_allocator，但是static_large_allocator粒度是page_size，这样粒度是不是太大了？还有需要用小内存分配用哪一个allocator比较好。（另外在我的应用中都是先传一个大buffe给allocator，完全有allocator管理）

**Comment by waruqi** [comment]
只不过是复用了 static_large_allocator 里面的分配算法，初始化的时候，我已经吧 page_size 设置了 8bytes 了，不会太大。

https://github.com/tboox/tbox/blob/5dfa3d9170c0e4198b92a60a934c1ace650b68f2/src/tbox/memory/static_allocator.c#L82-L85

**Comment by tangaoo** [comment]
有几点没有理解。

1. 没有理解next_head，为啥会多移动一个sizeof(data_head)。

`                    tb_static_large_data_head_t* next_head = (tb_static_large_data_head_t*)((tb_byte_t*)(data_head + 1) + space);
                    next_head->space = data_space - space - sizeof(tb_static_large_data_head_t);`
2. 为啥pagesize要大于sizeof(tb_static_large_data_head_t)，还有该结构体中base成员是做什么的？
3. 读了一遍代码，还没完全理解static_large_allocator算法，看上去就是在一个线性连续内存上不断通过移动data_head来实现分配的，是这样吗？

**Comment by waruqi** [comment]
> 没有理解next_head，为啥会多移动一个sizeof(data_head)。
tb_static_large_data_head_t* next_head = (tb_static_large_data_head_t*)((tb_byte_t*)(data_head + 1) + space); next_head->space = data_space - space - sizeof(tb_static_large_data_head_t);

data_head 指向的 free buffer 带大了，分配出开头部分free space后，剩余的free buffer 切割出来作为独立的 free block 

next_head指向的就是分割后，剩余free buffer 的起始 head，并没有多移动，只不过是挪到被分配出去的space 之后的尾部位置

> 为啥pagesize要大于sizeof(tb_static_large_data_head_t)，还有该结构体中base成员是做什么的？

数据块按 pagesize 对齐分配的，最小buffer块也要 1 个 pagesize ，每个buffer 都要有个 tb_static_large_data_head_t 存储每个块的 size 等信息，太小了，连 tb_static_large_data_head_t 的空间都没有 

base 就是继承的 tb_pool_data_head_t 父类结构体，里面维护了 size 等每个内存块的通用数据信息

> 读了一遍代码，还没完全理解static_large_allocator算法，看上去就是在一个线性连续内存上不断通过移动data_head来实现分配的，是这样吗？

差不多就是这样，只不过会有些优化措施

1. free 后会自动 merge 相邻的 free space，减少内存碎片
2. 通过缓存free buffer 来预测下次可分配的 buffer，提高预测命中率，减少线性查找导致的效率问题（不过通常用于大块pagesize分配，碎片数不会太多，线性查找也不会太慢，而嵌入式设备上 预先传入的 总 buffer 也不会太大，加上1里面的 merge 算法，总体还可以）

而 default_allocator 会在这个 large allocator 的基础下，外加一层 fixed pool/small pool 的小块内存分配，来进一步减少碎片产生。

具体可以看下：https://tboox.org/cn/2016/02/04/memory-pool/

**Comment by tangaoo** [comment]
感谢riki耐心回答
