### ISSUE TITLE
tb_single_list_entry_remove_safe() 输入检查

### ISSUE THREAD

**Issue by tangaoo** [tboox/tbox#151]
```C
static __tb_inline__ tb_void_t                  tb_single_list_entry_remove_safe(tb_single_list_entry_head_ref_t list, tb_single_list_entry_ref_t prev, tb_single_list_entry_ref_t next)
{
    // check
	tb_assert(list && list->size && prev);

    // update last
    if (prev->next == list->last) list->last = next;

    // remove entries
    prev->next = next;

    // update size
    list->size--;
}
```
是否应该对该函数增加参数prve、next位置关系检查？

**Comment by waruqi** [comment]
? 你要怎么加？

**Comment by tangaoo** [comment]
按我的理解下面两种输入情况会产生错误：
1. prev = entry[last],  next = NULL；（prev是last entry，next是NULL）
2. prev = entry[n],  next = entry[n+1].（非法输入prev与next是相邻的两个entry）

**Comment by waruqi** [comment]
对这两种非法输入是会有问题，但对于 tb_single_list_entry_remove_safe 来说是没必要的。

因为，tb_single_list_entry_remove_safe 其实是不对外公开给用户调用的接口（属于内部调用接口），仅仅为了给下面这两个对外接口提供统一的实现，所以我带了 _safe 后缀，意思是假定输入参数是安全合法的，不再做过多额外的参数检查影响性能。

https://github.com/tboox/tbox/blob/870ba1ac8125bb299440f3752d02c0ac716f04ed/src/tbox/container/single_list_entry.h#L400-L420

对于用户，仅仅只允许调用上面这两个接口，对list的head节点，以及next节点进行移除，其输入参数仅仅只有 prev 或者 list 自身。。

因此，除非list本身的内部结构被破坏了，否则不会出现你说的上述两种情况，next永远不会是null，也不会传入 prev/next相邻。

而对于list本身结构被破坏的情况，那就属于其他异常问题了，不管怎么检查都避免不了出错，因为mem已经出问题了。

**Comment by tangaoo** [comment]
明白了您"_safe"的意思。
不过可能还是有问题，用户调tb_single_list_entry_remove_next()，输入prev=entry[last-1]时，会正常调用tb_single_list_entry_remove_safe()。此时传入tb_single_list_entry_remove_safe参数为prev=entry[last-1]， next=NULL。下面代码段应该有bug。此时会删除entry[last]，list->last = prev才对。
```C
    // update last
    if (prev->next == list->last) list->last = next;
```

**Comment by waruqi** [comment]
嗯，这里确实有点问题，我刚修复了，非常感谢~

**Comment by waruqi** [comment]
另外，为了避免歧义，tb_single_list_entry_remove_safe 接口我改成 tb_single_list_entry_remove_ 了，作为私有接口
