### ISSUE TITLE
关于list的itor的step大小问题

### ISSUE THREAD

**Issue by tangaoo** [tboox/tbox#152]
list中itor.step 大小是否应该为element.size + sizeof(tb_list_entry_t)，这样也和list_entry保持一致。个人理解哈。
源代码片段如下（src/tbox/container/single_list.c）：
```
list->itor.step = element.size;
```

**Comment by waruqi** [comment]
当前传入的 `list->itor.step = entry_size;` 中的 entry_size ，就是包含 tb_list_entry_t 的实际element type大小。。

https://github.com/tboox/tbox/blob/2c31b4f94a6a225248ea993080a30b98947c4b3c/src/tbox/container/list_entry.c#L144-L177

https://github.com/tboox/tbox/blob/2c31b4f94a6a225248ea993080a30b98947c4b3c/src/tbox/container/list_entry.h#L60-L87

**Comment by tangaoo** [comment]
对，list_entry和single_list_entry是没有问题；有异议的是list与single_list。
例如如下代码。
https://github.com/tboox/tbox/blob/2c31b4f94a6a225248ea993080a30b98947c4b3c/src/tbox/container/single_list.c#L233

**Comment by waruqi** [comment]
list/single_list 也没问题，跟 list_entry 模式不同，list_entry 是外置式的 element struct，不维护element buffer

list 内置的 element buffer 维护，所有非 _entry的容器，比如 queue/vector/list/single_list 都是内置element buffer，所以都是设置的 element.size

**Comment by tangaoo** [comment]
按我的理解，这个step是后面迭代器做偏移用的。本来list上面的一个节点大小是element+entry（数据本身大小+节点指针大小），现在step仅仅赋值element的大小。这样后面迭代器做偏移不是会有问题吗？不过我找了一下，后面好像也没用到这个step。

**Comment by waruqi** [comment]
> 按我的理解，这个step是后面迭代器做偏移用的。本来list上面的一个节点大小是element+entry（数据本身大小+节点指针大小），现在step仅仅赋值element的大小。这样后面迭代器做偏移不是会有问题吗？不过我找了一下，后面好像也没用到这个step。

不是的，迭代器靠偏移去迭代，那就只能支持 vector 这种连续buffer 维护的，像 list 这种 链表结构，怎么支持？

迭代器迭代只通过 next/prev callback来，跟偏移没关系，这里的step 就是指一个元素的实际大小。 也就一些 algorithm在交换elements时候会用到

**Comment by tangaoo** [comment]
大概明白了，我在看看代码，感谢回复！
