### ISSUE TITLE
请教element抽象层用意

### ISSUE THREAD

**Issue by tangaoo** [tboox/tbox#153]
1. 没有体会到您抽象各种基本数据类型作为element的用意。我仔细看了代码，容器里面迭代器在回调element里的方法，感觉还是没有get到您代码精髓。
2. 对element的接口实现也不太理解，比如uint8的copy。为啥要强制把形参data指针类型转成uint8？为啥不直接把data定义成uint8类型，这是为了兼容其他element吗？为啥参数buff还是做指针寻址呢，不是直接uint8到uint8类型的赋值？
https://github.com/tboox/tbox/blob/2c31b4f94a6a225248ea993080a30b98947c4b3c/src/tbox/container/element/uint8.c#L69-L76
表达的有点乱，不好意思。

**Comment by waruqi** [comment]
因为要同时支持 int str ptr 还有 struct mem 的element，所以element buff必须取址

data 既可能是int for insert(list, (void*)122)    也可以是 str for  insert(list, "djdjjd") 或者是 struct addr, insert(list, &mystruct)

**Comment by tangaoo** [comment]
感谢回复！
