### ISSUE TITLE
在fixed_pool中init slot的几处疑问。

### ISSUE THREAD

**Issue by tangaoo** [tboox/tbox#156]
在看您fix_pool代码，下面几个地方有疑问，向您请教学习。
1. need_space是否要考虑，static_fixed_pool的head以及usedinfo大小？
https://github.com/tboox/tbox/blob/cdaab5cdfaf2a69d6155ff2dc747341719177636/src/tbox/memory/fixed_pool.c#L176

2. 同理，item_space是否也得像static_fixed_pool内部实现一样考虑对齐？
https://github.com/tboox/tbox/blob/cdaab5cdfaf2a69d6155ff2dc747341719177636/src/tbox/memory/fixed_pool.c#L173

3. 同理，下面check代码，是否也要考虑static_fixed_pool的head以及usedinfo大小？
https://github.com/tboox/tbox/blob/cdaab5cdfaf2a69d6155ff2dc747341719177636/src/tbox/memory/fixed_pool.c#L182

最重要的，**pool->slot_size有可能与实际slot分配的最大item个数可能不一致**。（但是好像也不会导致内存泄露或者不足，因为分配和释放都是有static_fixed_pool来执行的，而它有正确的item信息）

**Comment by waruqi** [comment]
> need_space是否要考虑，static_fixed_pool的head以及usedinfo大小？

不用，slot_size 原本就是参考值，不用保证里面一定要能分配这么多数量的 item，另外这里用的是 tb_allocator_large_malloc 走的大块页分配，最小 buffer 粒度就是一个pagesize，完全可以容纳 fixed_pool 的 head 和 usedinfo ，没必要额外去外面计算它们。

而且 通过 tb_allocator_large_malloc 实际分配返回的  real_space 还可能比 need_space 大那么半个 pagesize ，所以基本不用担心不够 static_fixed_pool 的 meta 数据存储。

https://github.com/tboox/tbox/blob/cdaab5cdfaf2a69d6155ff2dc747341719177636/src/tbox/memory/fixed_pool.c#L180

> 同理，item_space是否也得像static_fixed_pool内部实现一样考虑对齐？

不用，这里只是为了计算大概需要分配给 slot 的总空间而已，实际每个item 的分配，tb_static_fixed_pool 里面会考虑对齐问题

> 同理，下面check代码，是否也要考虑static_fixed_pool的head以及usedinfo大小？

这里只是也粗略的检测下而已，没必要把 static_fixed_pool 的内部head占用细节暴露给外层的 模块来做检测，过于耦合。。

而且 tb_static_fixed_pool_init 内部自己也会去实际做检测，如果真的因为 head 不够，你再外面检测触发 assert break 和 tb_static_fixed_pool_init 里面检测失败，返回null，同样也能出来下面的 assert break，效果都是一样的，没有本质区别

https://github.com/tboox/tbox/blob/cdaab5cdfaf2a69d6155ff2dc747341719177636/src/tbox/memory/fixed_pool.c#L187

**Comment by tangaoo** [comment]
感谢waruqi的耐心讲解~
