### ISSUE TITLE
ISO C conformance

### ISSUE THREAD

**Issue by FrankHB** [tboox/tbox#158]
### Describe the bug
Reserved identifiers containing `__` (e.g. `__tb_inline__`) are introduced in the source code. This is not conforming to ISO C.

For inlining this is particluar bad because `inline` in the standards and different dialects have subtle differences. For example, ISO C99 `extern inline` is essentially confusing compared to GNU C89 and ISO C++'s rules. Blindly adding a new reserved identifier is more confusing, in particluar this project has nothing to do with a custom C implementation (which has its own rights to use reserved identifier naturally.)

### Expected behavior
There shall be no `__` in the code, except a few exceptions: the standard ones (`__FILE__`, etc.) and compiler magics like `__builtin_addressof` (still not related to portable C code ... no clues for better examples for the latter).

In particlar, potable C code should not *introduce* reserved identifiers.

### Error output
N/A.

### Related Environment
Every configurations seems to be supported here.

### Additional context
There seems no documentation about baseline of the conformance. So I think ISO C is the default.

I have not seen many projects with portable C support in mind. But even the ones emphasized it could be wrong, e.g. FreeType2 fixed the reserved identifiers in the header inclusion guards years ago. (This is not the issue in this project, though.)

**Comment by FrankHB** [comment]
BTW, although not a bug, the style is somewhat problematic if potability is notable. (Maybe better to comment [here] (https://tboox.org/cn/2016/07/29/code-style/) but I have some network issues for that site...)

Notably, abuse of `*_t` for fundamental types is bad. (Note the file scope `_t` types are reserved by POSIX. Nontheless, since non-POSIX platforms are also supported here, this is not that bad as `__`.)

I'm not argue for [the Linux kernel style](https://www.kernel.org/doc/html/v4.10/process/coding-style.html#typedefs) (and I actually think it is *wrong* by ignorance of the role of opaque type aliases for the portability sake), but a `typedef` name always identical to some more canonical types brings nothing than confusing, and it has indeed no difference to the confusion brough by MS's UPPER cases (except MS had probably enjoyed people with strong flavor of PASCAL names in the old time). Use of glib's `g` types are also [discoraged](https://stackoverflow.com/questions/31917108/what-is-the-purpose-of-using-glib-typedefs-gint-etc) nowadays. (It is worse that there are `gchar` and `guchar` but not `gschar`, and people can be misinformed that `signed char` and `char` are the same...)

For a specific example, I feel something goes wrong that I can't find the main function in xmake by a simple `rg -U 'int[\n ]+main' core`... Is there any `argc` not typed `int` ever supported? Or should I assume there is a possibility that `tb_int_t` could be something like `void`?

**Comment by waruqi** [comment]
既然是国人，我这就直接中文回了，en文水平不行，见谅~

> Reserved identifiers containing __ (e.g. __tb_inline__) are introduced in the source code. This is not conforming to ISO C.

For inlining this is particluar bad because inline in the standards and different dialects have subtle differences. For example, ISO C99 extern inline is essentially confusing compared to GNU C89 and ISO C++'s rules. Blindly adding a new reserved identifier is more confusing, in particluar this project has nothing to do with a custom C implementation (which has its own rights to use reserved identifier naturally.)

tbox的所有定义和函数都是带有 tb_ 前缀的，即使使用 __ 也是带有固定 __tb_ 来避免一些冲突，所以虽然不能保证 100% ，但基本上问题也不大，而定义 __tb_inline__ 就是为了消除一些差异性，当然用户可以不用它，通常主要用于tbox库内部。

如果说不符合iso c，这个我无所谓，我并不care这个。

> There shall be no __ in the code, except a few exceptions: the standard ones (__FILE__, etc.) and compiler magics like __builtin_addressof (still not related to portable C code ... no clues for better examples for the latter).

In particlar, potable C code should not introduce reserved identifiers.

理论上是这样的，我也知道，但是为了保证跟 tbox 的命令风格一致，我还是想用，这样看着顺眼些，__tb_ 如果这样还是会带来一些隐患冲突，那也没办法

> For a specific example, I feel something goes wrong that I can't find the main function in xmake by a simple rg -U 'int[\n ]+main' core... Is there any argc not typed int ever supported? And should I assume there is a possibility that tb_int_t could be something like void for the return type (if argc should just be a plain int)?

tbox里面里面也就唯一一个demo example用了，仅仅只是为了跟整体库风格保持一致，自己看着顺眼，用户想用int main，自己随意，tbox又不会强制用户改成tb_int_t main，没错，xmake里面的main我也用了，如果觉得这个给你带来了困扰，很抱歉，但这并不是什么大问题

> Notably, abuse of *_t for fundamental types is bad. (Note the file scope _t types are reserved by POSIX. Nontheless, since non-POSIX platforms are also supported here, this is not that bad as __ for conformance reasons.)

所以我都是加了 tb_ 开头的，确保没有跟posix的冲突

> One more thing: [u]intN_t is intentially optional in C99 (and C++11). They shall be missing when the aliased types are not available natively. For more compatibility when the size is not required in the interface, use [u]intN_[least|fast]_t instead. If this is not the case (for pre-C99 and pre-C++11 environments), just provide complement implementations exactly conform to the standard interface.

所以这就是为什么我不用intN_t 这些，只用自己定义的tb_intN_t 来确保最好的兼容性，至少能保证任何时候都是可用的

**Comment by FrankHB** [comment]
Then please document your decisions explicitly to prevent the confusion on the availability.
