### ISSUE TITLE
large static allocator中data_tail有效前，已经被调用了

### ISSUE THREAD

**Issue by tangaoo** [tboox/tbox#162]
tbox库很棒！
发现一个小问题，如下data_tail在964行赋有效值，但是在961行函数内部已经用到了data_tail，是否交换下顺序更合理呢。
https://github.com/tboox/tbox/blob/a175e44090dac8891769d28968a7c06191b1813f/src/tbox/memory/impl/static_large_allocator.c#L961-L964

**Comment by waruqi** [comment]
这个在 tb_static_large_allocator_init 初始化阶段，其实这两行换不换位置，效果都是一样的。

前面有对 allocator->data_tail 做 tb_null 的初始化。

https://github.com/tboox/tbox/blob/a175e44090dac8891769d28968a7c06191b1813f/src/tbox/memory/impl/static_large_allocator.c#L916-L917

所以，不换的情况，tb_static_large_allocator_pred_update  里面 `data_head != allocator->data_tail` 就是，`allocator->data_head != tb_null` ，永远是 true

即使换了下，`data_head != allocator->data_tail` 就是，`allocator->data_head != (tb_byte_t*)&allocator->data_head[1] + xxx` ，也永远是 true

实际上，在init 阶段，下面这个判断是可有可无的，因为传入的首个 data_head 也就是 allocator->data_head 永远是有效的。

https://github.com/tboox/tbox/blob/a175e44090dac8891769d28968a7c06191b1813f/src/tbox/memory/impl/static_large_allocator.c#L255-L256

只不过我不想为此再去额外定义的 tb_static_large_allocator_pred_update2 去特殊处理了（干掉这个check），反正这行的 check 其实完全没任何影响，所以在 init 里面，放哪里掉 tb_static_large_allocator_pred_update 都 ok

所以暂时我不去动这个了，除非真的存在干扰正常运行的 bug。

**Comment by tangaoo** [comment]
感谢回复！
明白你的意思了。
