### ISSUE TITLE
关于file、socket等等流的继承方式选择问题

### ISSUE THREAD

**Issue by tangaoo** [tboox/tbox#163]
tbox库很棒！
请教ruki一个小问题，如下：

https://github.com/tboox/tbox/blob/a175e44090dac8891769d28968a7c06191b1813f/src/tbox/stream/impl/stream/file.c#L39-L68
为啥file、socket等等流的继承没有采用如下形式呢，是有其他考虑吗？（代码中很多其他模块是这种结构）
```C
typedef struct __tb_stream_data_t
{
    tb_stream_t           base;
    xxx;
    xxx;
}tb_stream_data_t;
```

**Comment by waruqi** [comment]
也是这种模式，只不过没有显式的在 struct 中定义，在 tb_stream_init 会去追加 stream_t base 

https://github.com/tboox/tbox/blob/a175e44090dac8891769d28968a7c06191b1813f/src/tbox/stream/stream.c#L70

**Comment by tangaoo** [comment]
感谢回复！
是的，我也看到了这里，程序功能是没有问题的。我想表达是，没有统一风格是有其他考虑，还是说仅仅是历史原因。哈哈哈

**Comment by waruqi** [comment]
故意为止，为了提供 tb_stream_init 接口让用户可以更加方便的扩展定义自己的 stream 

但是又不想将 tb_stream_t 的具体定义暴露出来(包括对应的私有头文件)，仅作为内部实现使用

所以我们仅仅给用户暴露去掉实际定义的 tb_stream_ref_t 抽象引用类型，因此用户也不用在自定义的stream type里面定义base，这样也方便用户使用，减少躺坑

比如这里定义的一个扩展stream

https://github.com/tboox/tbox/blob/a175e44090dac8891769d28968a7c06191b1813f/src/tbox/database/impl/mysql.c#L310

**Comment by tangaoo** [comment]
明白了。感谢回复哈
