### ISSUE TITLE
项目使用xmake依赖tbox,安装的时候会出现错误

### ISSUE THREAD

**Issue by a952135763** [tboox/tbox#164]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题

项目使用xmake依赖tbox,安装的时候会出现错误

### 期待的结果

应该能安装成功

### 错误信息
运行错误信息:

` Executing task: xmake f -p mingw -a x86 -m release -o "d:\git\gcctest/build" <
checking for mingw directory ... D:\i686-8.1.0-win32-dwarf-rt_v6-rev0\mingw32
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> mbedtls 2.13.0 
  -> zlib 1.2.11 
  -> tbox v1.6.6 [charset:y, coroutine:y, object:y, zlib:y, hash:y, mbedtls:y, zip:y, xml:y, regex:y]
please input: y (y/n)

  => download https://github.com/madler/zlib/archive/v1.2.11.tar.gz .. ok
  => install zlib 1.2.11 .. ok
  => download https://github.com/tboox/tbox/archive/v1.6.6.tar.gz .. ok
  => download https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.13.0.zip .. ok
package(mbedtls) is being accessed by other processes, please waiting!
  => install mbedtls 2.13.0 .. ok
  => install tbox v1.6.6 .. failed
if you want to get verbose errors, please see:
  -> C:\Users\CY\AppData\Local\.xmake\cache\packages\2101\t\tbox\v1.6.6\installdir.failed\logs\install.txt
error: install failed!
`

install.txt 文件内容

`assertion failed!
`
### 相关环境
我使用的是mingw编译

经过测试 使用默认本机的windows vs2019 也编译不通过
install.txt 内容一样
### 其他信息

无

**Comment by waruqi** [comment]
xmake f 的时候追加 -vD -c 给我看下完整错误和栈

**Comment by a952135763** [comment]
从install ok开始截取
`install ok!
finding tbox from xmake ..
checking for xmake::tbox ... tbox v1.6.6
{ 
  sysincludedirs = {
    "C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\32d019d364ad46d197fb082c232cea1b\include"
  },
  syslinks = {
    "ws2_32",
    "user32",
    "kernel32"
  },
  links = {
    "tbox"
  },
  static = true,
  libfiles = {
    "C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\32d019d364ad46d197fb082c232cea1b\lib\tbox.lib"
  },
  linkdirs = {
    "C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\32d019d364ad46d197fb082c232cea1b\lib"
  }
}

patching C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\32d019d364ad46d197fb082c232cea1b\lib\pkgconfig\tbox.pc ..
checking for link.exe ... D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\link.exe
checking for the linker (ld) ... link.exe
checking for cl.exe ... D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\cl.exe
checking for the c compiler (cc) ... cl.exe
checking for D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\cl.exe ... ok
checking for flags (/MT) ... ok
> cl.exe "/MT" "-nologo"
checking for flags (-TP) ... ok
> cl.exe "-TP" "-nologo"
checking for flags (cl_external_includedir) ... ok
> cl.exe "-experimental:external" "-external:W0" "-external:IC:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\32d019d364ad46d197fb082c232cea1b\include" "-nologo"
> "D:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\cl.exe" -c -nologo /MT -TP -experimental:external -external:W0 -external:IC:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\32d019d364ad46d197fb082c232cea1b\include -FoC:\Users\CY\AppData\Local\Temp\.xmake\210129\_1604ADFB347F4310832024FAFD36BC50.o C:\Users\CY\AppData\Local\Temp\.xmake\210129\_6074363EB05D43108848A074A47BE730.c
checking for D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\link.exe ... ok
checking for flags (-nodefaultlib:msvcrt.lib) ... ok
> link.exe "-nodefaultlib:msvcrt.lib" "-nologo" "-dynamicbase" "-nxcompat" "-machine:x64"
> "D:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX64\\x64\\link.exe" -nologo -dynamicbase -nxcompat -machine:x64 -nodefaultlib:msvcrt.lib -libpath:C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\32d019d364ad46d197fb082c232cea1b\lib tbox.lib ws2_32.lib user32.lib kernel32.lib ntdll.lib -out:C:\Users\CY\AppData\Local\Temp\.xmake\210129\_72062843F7BF43108C745EB972593230.b C:\Users\CY\AppData\Local\Temp\.xmake\210129\_1604ADFB347F4310832024FAFD36BC50.o
> checking for c includes(tbox/tbox.h)
> checking for c funcs(tb_exit)
> checking for c links(tbox, ws2_32, user32, kernel32)
> checking for c snippet(has_cfuncs)
checkinfo: ...gramdir\core\sandbox\modules\import\core\tool\linker.lua:91: @programdir\modules\core\tools\link.lua:153: tbox.lib(tbox.c.obj) : 找到 MSIL .netmodule 或使用 /GL 编译的模块；正在使用 /LTCG 重新启动链接；
将 /LTCG 添加到链接命令行以改进链接器性能

stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:787]: in function 'raise'
    [@programdir\modules\core\tools\link.lua:153]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\modules\core\tools\link.lua:134]:
    [C]: in function 'link'
    [...gramdir\core\sandbox\modules\import\core\tool\linker.lua:89]: in function 'link'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:202]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\lib\detect\check_cxsnippets.lua:192]: in function 'has_cfuncs'
    [....xmake\repositories\xmake-repo\packages\t\tbox\xmake.lua:68]: in function 'script'
    [...gramdir\actions\require\impl\actions\..\utils\filter.lua:125]: in function 'call'
    [@programdir\actions\require\impl\actions\test.lua:50]: in function 'test'
    [@programdir\actions\require\impl\actions\install.lua:203]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\actions\require\impl\actions\install.lua:127]: in function 'action_install'
    [@programdir\actions\require\impl\package.lua:831]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:193]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:186]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

error: ....xmake\repositories\xmake-repo\packages\t\tbox\xmake.lua:68: assertion failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:787]: in function 'raiselevel'
    [@programdir\core\sandbox\modules\utils.lua:183]: in function 'assert'
    [....xmake\repositories\xmake-repo\packages\t\tbox\xmake.lua:68]: in function 'script'
    [...gramdir\actions\require\impl\actions\..\utils\filter.lua:125]: in function 'call'
    [@programdir\actions\require\impl\actions\test.lua:50]: in function 'test'
    [@programdir\actions\require\impl\actions\install.lua:203]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\actions\require\impl\actions\install.lua:127]: in function 'action_install'
    [@programdir\actions\require\impl\package.lua:831]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:193]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:186]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

  => install tbox v1.6.6 .. failed
error: @programdir\modules\private\async\runjobs.lua:217: @programdir\actions\require\impl\actions\install.lua:256: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:787]: in function 'raise'
    [@programdir\actions\require\impl\actions\install.lua:256]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:127]: in function 'try'
    [@programdir\actions\require\impl\actions\install.lua:127]: in function 'action_install'
    [@programdir\actions\require\impl\package.lua:831]: in function 'jobfunc'
    [@programdir\modules\private\async\runjobs.lua:193]:
    [C]: in function 'trycall'
    [@programdir\core\sandbox\modules\try.lua:121]: in function 'try'
    [@programdir\modules\private\async\runjobs.lua:186]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:317]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:787: in function 'raise'
        @programdir\modules\private\async\runjobs.lua:217: in function 'catch'
        @programdir\core\sandbox\modules\try.lua:127: in function 'try'
        @programdir\modules\private\async\runjobs.lua:186: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>
`

**Comment by waruqi** [comment]
你先切到 tbox debug 版本试试。。add_requires("tbox", {debug = true})

**Comment by a952135763** [comment]
嗯 我删除掉xmake得缓存目录 又能重新构建了...

**Comment by waruqi** [comment]
好吧，那就暂时没问题了哦？

**Comment by a952135763** [comment]
貌似原因是 mingw 生成得时候 会强制启用 __tb_small__ 宏(没法关闭)
这时候我开启其他 package 就会生成出错

**Comment by waruqi** [comment]
这跟small似乎没啥关系。。如果你这能复现，可以给个复现步骤

**Comment by a952135763** [comment]
这么添加依赖
`add_requires("tbox", {debug = false ,config = { 
    mbedtls = true ,
    zlib = true ,
    coroutine = true,
    hash = true,
    zip = true ,
    xml = true,
    regex = true,
    charset = true,
    object = true,
    }})`
使用mingw 我这边 无法生成，已经清除过缓存  使用vs又能生成 不晓得啥子原因

**Comment by waruqi** [comment]
那就是 vs 可以了？ mingw 不行？ 继续给下 mingw 时候的 详细错误信息。。`xmake f -c -p mingw --mingw=/xx -vD`

**Comment by a952135763** [comment]
[log.log](https://github.com/tboox/tbox/files/5902314/log.log)
这是全部日志
运行得命令
xmake f -c -p mingw -vD -a i386 -y >d:\log.log

**Comment by waruqi** [comment]
> C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(adler32.c.obj):adler32.c:(.text+0x17): undefined reference to `adler32'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x204): undefined reference to `mbedtls_ssl_handshake'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x2a2): undefined reference to `mbedtls_ssl_close_notify'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x2ee): undefined reference to `mbedtls_ssl_session_reset'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x32d): undefined reference to `mbedtls_ssl_read'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x3bc): undefined reference to `mbedtls_ssl_write'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x55a): undefined reference to `mbedtls_x509_crt_free'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x562): undefined reference to `mbedtls_ssl_free'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x570): undefined reference to `mbedtls_entropy_free'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x57e): undefined reference to `mbedtls_ctr_drbg_free'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x58c): undefined reference to `mbedtls_ssl_config_free'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x5f1): undefined reference to `mbedtls_x509_crt_init'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x5ff): undefined reference to `mbedtls_ctr_drbg_init'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x607): undefined reference to `mbedtls_ssl_init'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x618): undefined reference to `mbedtls_entropy_init'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x639): undefined reference to `mbedtls_entropy_func'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x641): undefined reference to `mbedtls_ctr_drbg_seed'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x64e): undefined reference to `mbedtls_test_cas_pem_len'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x656): undefined reference to `mbedtls_test_cas_pem'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x662): undefined reference to `mbedtls_x509_crt_parse'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x678): undefined reference to `mbedtls_ssl_config_init'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x69d): undefined reference to `mbedtls_ssl_config_defaults'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x6b9): undefined reference to `mbedtls_ssl_conf_min_version'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x6c9): undefined reference to `mbedtls_ssl_conf_authmode'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x6dd): undefined reference to `mbedtls_ssl_conf_ca_chain'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x6eb): undefined reference to `mbedtls_ctr_drbg_random'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x6f7): undefined reference to `mbedtls_ssl_conf_rng'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x703): undefined reference to `mbedtls_ssl_setup'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(mbedtls.c.obj):mbedtls.c:(.text+0x184): undefined reference to `mbedtls_ssl_set_bio'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(gzip.c.obj):gzip.c:(.text+0x6c): undefined reference to `deflate'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(gzip.c.obj):gzip.c:(.text+0x101): undefined reference to `inflate'
C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib/tbox.lib(gzip.c.obj):gzip.c:(.text+0x154): undefined reference to `inflateEnd'
C:\Users\CY\AppDat

这是由于 你启用了，zlib/mbedtls模块，xmake-repo/tbox包里面暂时没加这些依赖导致。我更新了包，再试试

```console
xmake repo -u
xmake f -c xxxxxxxxx ....
xmake
```

**Comment by a952135763** [comment]
OK 已经解决 能正常生成了
