### ISSUE TITLE
xmake 编写静态库使用add_files打包tbox出现的问题

### ISSUE THREAD

**Issue by a952135763** [tboox/tbox#165]
### 描述问题
使用如下配置生成...重新打包静态库
`target("clib_static")
    set_kind("static")
    add_packages("tbox")
    --打包静态库
    add_files("lib/tbox.lib")
    add_headerfiles("h/*.h")
    add_files("*.cpp")`
运行命令`xmake -vD`
### 期待的结果

能正常合并静态库

### 错误信息

发生如下错误
[error.log](https://github.com/tboox/tbox/files/5903012/error.log)
这是部分重点错误信息
`error: @programdir\modules\private\async\runjobs.lua:217: @programdir\rules\utils\merge_archive\merge_archive.lua:47: object name(random.c.obj) conflicts in library: C:\Users\CY\AppData\Local\.xmake\packages\t\tbox\v1.6.6\ec6579d0529a425eb053f9daadeca544\lib\tbox.lib`

**Comment by waruqi** [comment]
尽量走 add_links ，不要走merge。。merge库，需要拆包lib，抽取obj后在合并，会丢失 obj 的路径结构信息，如果lib里面有重名的obj 就会合并失败，有冲突。。这个没法解。 linux 下 .a 库也是。。
