### ISSUE TITLE
element_str 是否存在 free 静态内存的风险？

### ISSUE THREAD

**Issue by tangaoo** [tboox/tbox#171]
hi, ruki. 把各数据类型抽象成 element 实现类似模板的功能，太巧妙了，受益匪浅。

对于 str element 的 free 接口有一个疑问，**这样是不是存在释放静态内存的可能**? 但我尝试了demo程序，却并没有问题，很费解。

https://github.com/tboox/tbox/blob/5ef932750ede0b90867fd4afdcf1deed2464c82b/src/tbox/container/element/str.c#L63-L71

**Comment by waruqi** [comment]
str都是内部分配的，为啥会 free 到静态内存？

**Comment by tangaoo** [comment]
@waruqi 感谢回复！
您说得是对的。原来 str的插入都是 duplicate 一遍的。

还有一个问题，对于 element 相关接口，形参都用了 void* ，有点分不清是传 data变量，还是data指针变量，或者是data指针的指针变量。是不是如下，**buffer就是data指针变量， data就是data呢？这些接口都不存在有 data指针的指针变量吧**？（这里data 指的是例如 int8 char* ptr等）
https://github.com/tboox/tbox/blob/5ef932750ede0b90867fd4afdcf1deed2464c82b/src/tbox/container/element/str.c#L73

**Comment by waruqi** [comment]
data看element的类型，可能是 ptr 也可能是 int 

buffer是 element的存储buff，永远是地址

**Comment by tangaoo** [comment]
明白了，感谢哈~
