### ISSUE TITLE
c17 c18 support

### ISSUE THREAD

**Issue by laoshaw** [tboox/tbox#181]
### Is your feature request related to a problem? Please describe.

I replaced c99 in xmake.lua with c17 or c18 and it refused to take with with a hint "do you mean c11"

### Describe the solution you'd like

support c17 and c18

**Comment by waruqi** [comment]
Why switch to c17 when it can already be compiled with c99. in addition, c17/18 works for me.

**Comment by laoshaw** [comment]
yes on x86 it built fine with c17/c18, my cross compiler can only do c99/c11, anyway I will live with that.
