### ISSUE TITLE
V1.6.9 compile error: implicit declaration of function 'YieldProcessor' 

### ISSUE THREAD

**Issue by wzhy** [tboox/tbox#189]
### issue
My OS: Windows 10 home 21H2，64bit; CPU: AMD Ryzen 7 5800H; Compiler: [TDM-GCC(](https://jmeubank.github.io/tdm-gcc/download/)32bit, GCC version is 10.3.0).
The configure comand is: 
`xmake f -p mingw --sdk=C:\TDM-GCC-32 --arch=i386 --polarssl=false --sqlite3=false --openssl=false --mysql=false --zlib=false`
Then `xmake` and it's outputs as bellow:

[  0%]: ccache compiling.release src\tbox\tbox.c
[  0%]: ccache compiling.release src\tbox\libc\stdio\putchar.c
[  0%]: ccache compiling.release src\tbox\math\impl\math.c
[  0%]: ccache compiling.release src\tbox\libc\stdio\printf_object.c
[  0%]: ccache compiling.release src\tbox\libc\stdio\puts.c
[  0%]: ccache compiling.release src\tbox\libc\stdio\printf.c
[  0%]: ccache compiling.release src\tbox\libc\stdio\sprintf.c
[  0%]: ccache compiling.release src\tbox\hash\adler32.c
[  0%]: ccache compiling.release src\tbox\math\random\random.c
[  0%]: ccache compiling.release src\tbox\libc\misc\time\localtime.c
[  0%]: ccache compiling.release src\tbox\hash\bkdr.c
[  0%]: ccache compiling.release src\tbox\libc\misc\time\time.c
[  0%]: ccache compiling.release src\tbox\libc\misc\time\mktime.c
[  0%]: ccache compiling.release src\tbox\libc\impl\libc.c
[  0%]: ccache compiling.release src\tbox\hash\fnv32.c
[  0%]: ccache compiling.release src\tbox\libc\stdio\snprintf.c
[  0%]: ccache compiling.release src\tbox\math\int32.c
[  0%]: ccache compiling.release src\tbox\libc\misc\time\gmmktime.c
[  0%]: ccache compiling.release src\tbox\libc\stdio\swprintf.c
[  0%]: ccache compiling.release src\tbox\math\fixed16.c
[  0%]: ccache compiling.release src\tbox\math\random\linear.c
[  0%]: ccache compiling.release src\tbox\libc\stdio\vsnprintf.c
[  0%]: ccache compiling.release src\tbox\libc\misc\time\gmtime.c
[  0%]: ccache compiling.release src\tbox\libc\stdio\getchar.c
[  0%]: ccache compiling.release src\tbox\libc\stdio\vswprintf.c
[  1%]: ccache compiling.release src\tbox\libc\stdio\wprintf.c
[  1%]: ccache compiling.release src\tbox\libc\stdio\wputs.c
[  1%]: ccache compiling.release src\tbox\libc\stdlib\mbstowcs.c
[  2%]: ccache compiling.release src\tbox\libc\stdlib\random.c
[  2%]: ccache compiling.release src\tbox\libc\stdlib\stdlib.c
[  2%]: ccache compiling.release src\tbox\libc\stdlib\wcstombs.c
[  2%]: ccache compiling.release src\tbox\libc\string\memcmp.c
[  2%]: ccache compiling.release src\tbox\libc\string\memcpy.c
[  4%]: ccache compiling.release src\tbox\libc\string\memdup.c
[  4%]: ccache compiling.release src\tbox\libc\string\memmem.c
[  4%]: ccache compiling.release src\tbox\libc\string\memmov.c
[  4%]: ccache compiling.release src\tbox\libc\string\memset.c
[  4%]: ccache compiling.release src\tbox\libc\string\strcat.c
error: src\tbox\math\random\../../platform/sched.h:42:26: error: implicit declaration of function 'YieldProcessor' [-Werror=implicit-function-declaration]
   42 | #   define tb_sched_yield()             YieldProcessor()
        |                          ^~~~~~~~~~~~~~
src\tbox\math\random\../../platform/spinlock.h:141:9: note: in expansion of macro 'tb_sched_yield'
  141 |         tb_sched_yield();
         |         ^~~~~~~~~~~~~~
cc1.exe: all warnings being treated as errors
 > in src\tbox\math\random\random.c

=================
I tried release 1.6.8, but with the same problem.
Anyone HELP!
Thank you!
[tbox-1.6.9_CompileError.txt](https://github.com/tboox/tbox/files/9040114/tbox-1.6.9_CompileError.txt)

**Comment by waruqi** [comment]
你这的工具链 没这个接口，自己本地改下代码 https://github.com/tboox/tbox/blob/master/src/tbox/platform/sched.h#L42

**Comment by wzhy** [comment]
> 你这的工具链 没这个接口，自己本地改下代码 https://github.com/tboox/tbox/blob/master/src/tbox/platform/sched.h#L42

soloved.
Thanks.

**Comment by wzhy** [comment]
Use MSYS2 and then install `mingw-w64-i686-toolchain`  also works without modified any code.
`xmake global --mingw="C:\msys64\mingw32"`
