### ISSUE TITLE
mingw gcc 12.1.0 report dangling-pointer while compiling

### ISSUE THREAD

**Issue by wzhy** [tboox/tbox#196]
### Describe the bug
command:
`xmake g --mingw="C:\mingw32"`
`xmake f -p mingw --sdk="C:\mingw32" --arch=i386 --polarssl=false --sqlite3=false --openssl=false --mysql=false --zlib=false --xml=true --coroutine=true`
`xmake`

### Error output
... ...
```
[ 62%]: ccache compiling.release src\tbox\platform\windows\interface\ole32.c
[ 62%]: ccache compiling.release src\tbox\platform\windows\interface\shell32.c
[ 63%]: ccache compiling.release src\tbox\platform\windows\interface\user32.c
[ 63%]: ccache compiling.release src\tbox\platform\windows\interface\ws2_32.c
[ 64%]: ccache compiling.release src\demo\libc\mbstowcs.c
[ 63%]: ccache compiling.release src\demo\demo.c
error: src\tbox\coroutine\impl\stackless\../../stackless/core.h:100:32: error: storing the address of local variable '__tb_lo_core_label268' in '*(struct __tb_lo_core_t *)co__.branch' [-Werror=dangling-pointer=]
  100 |         tb_lo_core(co)->branch = &&__tb_mconcat_ex__(__tb_lo_core_label, __tb_line__); \
      |                                ^
src\tbox\coroutine\impl\stackless\../../stackless/coroutine.h:109:5: note: in expansion of macro 'tb_lo_core_record'
  109 |     tb_lo_core_record(co__); \
      |     ^~~~~~~~~~~~~~~~~
src\tbox\coroutine\impl\stackless\scheduler_io.c:268:17: note: in expansion of macro 'tb_lo_coroutine_yield'
  268 |                 tb_lo_coroutine_yield();
      |                 ^~~~~~~~~~~~~~~~~~~~~
In file included from d:\project\tbox-1.6.9\src\tbox\prefix/arch.h:28,
                 from d:\project\tbox-1.6.9\src\tbox\prefix/prefix.h:29,
                 from d:\project\tbox-1.6.9\src\tbox\prefix.h:27,
                 from src\tbox\coroutine\impl\stackless\../../prefix.h:27,
                 from src\tbox\coroutine\impl\stackless\../prefix.h:27:
src\tbox\coroutine\impl\stackless\../../stackless/core.h:99:27: note: '__tb_lo_core_label268' declared here
   99 |         __tb_mconcat_ex__(__tb_lo_core_label, __tb_line__): \
      |                           ^~~~~~~~~~~~~~~~~~
  > in src\tbox\coroutine\impl\stackless\scheduler_io.c
```

### Related Environment
windows 10 64bit, AMD 5800H, tbox-1.6.9
`gcc -v`
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/mingw32/bin/../libexec/gcc/i686-w64-mingw32/12.1.0/lto-wrapper.exe
OFFLOAD_TARGET_NAMES=nvptx-none
Target: i686-w64-mingw32
Configured with: ../configure --prefix=/R/winlibs32_stage/inst_gcc-12.1.0/share/gcc --build=i686-w64-mingw32 --host=i686-w64-mingw32 --enable-offload-targets=nvptx-none --with-pkgversion='MinGW-W64 i686-posix-dwarf, built by Brecht Sanders' --with-tune=generic --enable-checking=release --enable-threads=posix --with-dwarf2 --disable-sjlj-exceptions --disable-libunwind-exceptions --disable-serial-configure --disable-bootstrap --enable-host-shared --enable-plugin --disable-default-ssp --disable-rpath --disable-libstdcxx-debug --disable-version-specific-runtime-libs --with-stabs --disable-symvers --enable-languages=c,c++,fortran,lto,objc,obj-c++,jit --disable-gold --disable-nls --disable-stage1-checking --disable-win32-registry --disable-multilib --enable-ld --enable-libquadmath --enable-libada --enable-libssp --enable-libstdcxx --enable-lto --enable-fully-dynamic-string --enable-libgomp --enable-graphite --enable-mingw-wildcard --enable-libstdcxx-pch --enable-libstdcxx-time --with-mpc=/d/Prog/winlibs32_stage/custombuilt --with-mpfr=/d/Prog/winlibs32_stage/custombuilt --with-gmp=/d/Prog/winlibs32_stage/custombuilt --with-isl=/d/Prog/winlibs32_stage/custombuilt --enable-large-address-aware --enable-libstdcxx-backtrace --enable-install-libiberty --enable-__cxa_atexit --without-included-gettext --with-diagnostics-color=auto --enable-clocale=generic --with-libiconv --with-system-zlib --with-build-sysroot=/R/winlibs32_stage/gcc-12.1.0/build_mingw/mingw-w64 CFLAGS=-I/d/Prog/winlibs32_stage/custombuilt/include/libdl-win32
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.1.0 (MinGW-W64 i686-posix-dwarf, built by Brecht Sanders)

=========================
But MSVC 2017 build successed with command below:
`xmake f -p windows -a x86 --polarssl=false --sqlite3=false --openssl=false --mysql=false --zlib=false  --xml=true --coroutine=true`

**Comment by waruqi** [comment]
try pass `--cxflags="-Wno-error=dangling-pointer=" to `xmake f`

**Comment by wzhy** [comment]
> 

Build OK using this argument.
Thank you!

**Comment by wzhy** [comment]
@
