### ISSUE TITLE
日志问题，tb_trace_w和tb_trace_w怎么都不输出到日志呢

### ISSUE THREAD

**Issue by misskimi** [tboox/tbox#212]
需要配置什么么？调用这两个函数，都无法输出内容到日志里。

**Comment by waruqi** [comment]
https://docs.tboox.org/#/zh-cn/manual/basic

**Comment by misskimi** [comment]
只有tb_trace_i可以输出，tb_trace_w和tb_trace_e都不行

**Comment by waruqi** [comment]
目前 w/e 只会在 debug 模式下才会显示。。
