### ISSUE TITLE
UDP Server程序，在有的系统中tb_socket_urecv会一直返回0

### ISSUE THREAD

**Issue by wzhy** [tboox/tbox#215]
tbox版本是最新版1.7.3，开发平台是Visual Studio 2017，电脑是Windows 7_64bit，仿照tbox自带的Demo程序，使用协程API编写了一个UDP Server程序，只是单纯的接收数据。
最初一切正常，但是重装了系统（还是Windows 7_64bit）后，就出现无法收到数据的问题，断点跟进去发现tb_socket_urecv一直返回0。
换了台相同硬件配置的电脑，全新安装了Windows 10_64bit(版本号2022H2)，情况一样，tb_socket_urecv一直返回0。但是在另外一台Windows10_64bit(版本号2020)上，同样的程序又能正常收数。再找一台不同硬件配置的电脑，安装Windows 10_64bit(版本号2022H2)，tb_socket_urecv还是一直返回0。
所有电脑的驱动都安装齐全，没有病毒。用微软自家的[Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon)监视程序进程的网络状态。是可以看到有UDP数据进来的。
不知道有没有遇到过类似情况？怎么定位的？怎么解决的？
谢谢！

**Comment by waruqi** [comment]
没遇到过，你可以跟下源码。。

**Comment by wzhy** [comment]
> 没遇到过，你可以跟下源码。。

这个问题我跟进源码也没看出来原因。
后来我把单独在另外一个目录下的tbox源码用xmake编译成静态库后，把库和头文件拷贝到我的Visual Studio解决方案中，问题消失了。
发现还是tbox.config.h跟构建tbox时发生了变化，跟#211时一样的情况……
我这个解决方案本身也是xmake生成的，本来是tbox源码放到其中，以一种子项目的形式存在。
既然已经遇到了两次，感觉还是有些东西没搞清楚。那么我什么样的操作会引起tbox.config.h部分内容发生改变呢？

**Comment by waruqi** [comment]
xmake.lua 配置有改动，或者 xmake project 生成 vs 工程时候，都会触发重新配置。。

**Comment by wzhy** [comment]
> xmake.lua 配置有改动，或者 xmake project 生成 vs 工程时候，都会触发重新配置。。
这两个情况我是知道的，但是在我这里我没有再改动过xmake.lua，也没有重新生成VS工程，建好解决方案后只使用VS菜单中的“生成解决方案”、“清理解决方案”等操作，感觉应该和这些操作无关；
当然我也会修改项目的属性配置，比如“C/C++”->“代码生成”等选项，不知道是不是跟这些操作有关？

> 不建议在 vs 里面直接构建 tbox。。走 xmake 编译后，xmake install -o 导出库和头文件使用。。或者走 add_requires 包管理
我后来用的就是“xmake install -o 导出库和头文件使用”这种方法，好使。
