### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by duyanning** [tboox/tbox#218]
$ gcc --version
gcc (Debian 12.2.0-14) 12.2.0

![image](https://github.com/tboox/tbox/assets/748776/9f52c1d3-3bf3-42e4-9861-f4d3d17c2a80)

**Comment by waruqi** [comment]
更新到 dev 再试试

**Comment by duyanning** [comment]
> 更新到 dev 再试试

哇！好了！
祝作者 万寿无疆&永远在线
