### ISSUE TITLE
tb_oc_string_init_from_cstr没有将字符串中的\n转义为\\n

### ISSUE THREAD

**Issue by duyanning** [tboox/tbox#223]
### 描述问题

tb_oc_string_init_from_cstr
也许准确说是tb_object_writ_to_data(obj_msg, bufJson, sizeof bufJson, TB_OBJECT_FORMAT_JSON)
没有将字符串中的`\n`转义为`\\n`

### 期待的结果
json对象的字符串字段，如果该字符串中含有单个字符`\n`，
我希望在产生的json对象中，单个字符`\n`被转换为两个字符串：即单个字符`\\`与 单个字符`n`

### 错误信息

导致得到的字符串中含有`\n`而不是`\\n`
如下(注意pubKey字段，这个字符串中含有多个不可见的`\n`，它们应该是可见的`\\n`)
{
  "name": "REGISTER"
, "pubKey": "-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxtQ78zfTJOPhN/5jmX1k
pU7ELTPggvZjbeyti91j2ZiQfYm9FeS2qXrkrTwkDZpHT1XgPlcHutz+QhCAJ1ej
J1+1w3wtp/Mqho7JVEUXFlqPBxhVNYaeuJrxX3lk2jqwNHW/vk7PO/dDn8r1EDrV
FQckEWI2X2T5GP9bV4fEnUIHzZxHyucJGAf0kxQUxZ0F0x1NRQ9z6ula2RKsB48i

### 相关环境

请提供编译和运行环境信息。

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by waruqi** [comment]
之前没做转义，刚稍微搞了下，可以试试https://github.com/tboox/tbox/commit/a83fd7736b538153191e144cc87418d08701a556#diff-450eb88d32029322cda729d0ea85f19d3c31d09003458652a51fef7cb3bb3ee1

最近也没时间细搞，如果有问题，可以自己提 pr 过来改进
