### ISSUE TITLE
通过xrepo引入tbox 1.7.4，xmake config在wasm平台编译报错

### ISSUE THREAD

**Issue by darcy-shen** [tboox/tbox#226]
> 注：提问题时若使用`不能用/没效果/有问题/报错`此类模糊表达，但又没有根据下面的模板给出任何相关辅助信息的，将绝对不会有任何反馈。

### 描述问题
xmake config 失败

### 期待的结果
xmake config 成功

### 错误信息
```
error: @programdir/modules/private/async/runjobs.lua:256: @programdir/modules/private/action/build/object.lua:91: @programdir/modules/core/tools/gcc.lua:807: In file included from src/tbox/utils/trace.c:29:
src/tbox/utils/../platform/impl/mutex.h:33:13: fatal error: 'spinlock.h' file not found
   33 | #   include "spinlock.h"
      |             ^~~~~~~~~~~~
1 error generated.
```

### 相关环境
Ubuntu 22.04, emscritpen 3.1.42

### 其他信息
https://github.com/XmacsLabs/lolly/pull/92

**Comment by waruqi** [comment]
dev 分支我修复了，但是我不保证 wasm 版本能正常用，从来没在 wasm 里面测试过，可能部分模块是没实现的。

**Comment by darcy-shen** [comment]
我来测试 wasm 的可用性吧

**Comment by darcy-shen** [comment]
Fixed by https://github.com/tboox/tbox/commit/fd261c9035b93e01bd2437c9956a7a9f4a98a5b5 and https://github.com/tboox/tbox/commit/151fe7f214422b4253a9952d3481e7c6487ee0e3
