### ISSUE TITLE
Implement `SortedDictionary` / `std::map` / `GTree` equivalent

### ISSUE THREAD

**Issue by iahung2** [tboox/tbox#239]
https://github.com/fusionlanguage/fut/issues/91

**Comment by waruqi** [comment]
std::map -> https://github.com/tboox/tbox/blob/master/src/tbox/container/hash_map.h

**Comment by pfusik** [comment]
`hash_map.h` looks like `Dictionary` / `std::unordered_map`.
`SortedDictionary` / `std::map` defines iteration in the order of keys.

**Comment by waruqi** [comment]
no sorted map and tree now.

**Comment by iahung2** [comment]
> no sorted map and tree now.

Please implement it. Thank you.
