### ISSUE TITLE
IOCP in Windows

### ISSUE THREAD

**Issue by Cheedoong** [tboox/tbox#24]
One drawback of glib is that it does not support IOCP in Windows. 
I hope you will consider about implementing it.

**Comment by waruqi** [comment]
We will support iocp in the future. : )

**Comment by TitanSnow** [comment]
It seems that IOCP is only supported on Windows. I think to add it may reduce compatibility。

Correspondingly, there's <code>epoll</code> in Linux, <code>/dev/poll</code> in Solaris. They're all vary.

I think a new, unified, abstract, fast network model may be a better choice but it may be a hard work.

**Comment by waruqi** [comment]
@TitanSnow  tbox provide a unified and abstract [poller interface](https://github.com/tboox/tbox/blob/master/src/tbox/platform/poller.h) to wrap `epoll`, `poll`, `select` and `kqueue`. 

And I will continue to support iocp in future, but it may take some time.

**Comment by TitanSnow** [comment]
That sounds great:+1:

**Comment by waruqi** [comment]
@Cheedoong I've already supported IOCP for coroutine and poller on windows. You can download master version and try it.

**Comment by Cheedoong** [comment]
Great job! We will try it.
