### ISSUE TITLE
Getting the current directory of a file returns inconsistent results on macOS

### ISSUE THREAD

**Issue by paradisuman** [tboox/tbox#241]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug
When I use the tb_directory_current ,it returns /private/tmp/xxxx. 
I use tb_directory_current_set to another dir, then I use  /tmp/xxxx to back, but tb_directory_current returns /private/tmp/xxxx without /private. 

### Expected behavior
We expect tb_directory_current to return the same dir.

### Error output
It returns /private/tmp/xxxx at beginning, /tmp/xxxx when we back to the same dir.

### Related Environment
It occurs on macOS.

### Additional context
See https://github.com/XmacsLabs/lolly/pull/173

**Comment by waruqi** [comment]
It works for me.

```
ruki-2:xxx ruki$ xmake l 
xmake> os.curdir()
< "/private/tmp/xxx"
xmake> os.cd("~")
< "/private/tmp/xxx"
xmake> os.curdir()
< "/Users/ruki"
xmake> os.cd("/private/tmp/xxx")
< "/Users/ruki"
xmake> os.curdir()
< "/private/tmp/xxx"
```

**Comment by paradisuman** [comment]
I will try more to figure out whether it's my problem.

**Comment by paradisuman** [comment]
I'm sorry.I got the issue backward; when I enter a folder under /tmp, it returns the current address as /private/tmp

**Comment by waruqi** [comment]
```
 /tmp -> private/tmp
```

This is normal, `/tmp` just a symbolic link on macOS. In addition, tbox is simply calling the `chdir` and `getcwd` apis.

**Comment by paradisuman** [comment]
Thanks for your explanation！
