### ISSUE TITLE
Hope tbox supports more compilation tools

### ISSUE THREAD

**Issue by WangZhongDian** [tboox/tbox#265]
# Current situation
I'm not sure if tbox can only be integrated through xmake, but when I installed it using xmake source code and tried to compile a demo using gcc, I got the following error
```shell
/bin/ld: /tmp/ccgXEPCN.o: in function `main':
main.c:(.text+0x28): undefined reference to `tb_init_'
/bin/ld: main.c:(.text+0x51): undefined reference to `tb_trace_done'
/bin/ld: main.c:(.text+0x56): undefined reference to `tb_exit'
collect2: error: ld returned 1 exit status
```
However, the installation documentation was compiled and used with xmake to obtain the correct results

# platform
- ubuntu24.04
- x86-64

# Installation command
```shell
xmake
xmake install
```

# hope
- I hope it can be installed directly on the system, compiled and linked directly for use
- If possible, I hope to support Conan

Finally, thank you very much for your efforts and dedication

**Comment by waruqi** [comment]
you need add `-ltbox` flags to linker. I don't know how do you use it in your project.

**Comment by WangZhongDian** [comment]
@waruqi 
![截图 2024-09-15 20-44-42](https://github.com/user-attachments/assets/c3c7c412-f37e-4f93-863e-04a662d352ba)

**Comment by waruqi** [comment]
`-lm`

**Comment by WangZhongDian** [comment]
Thank you very much, you can now work normally.
