### ISSUE TITLE
检测并避免 复制父目录到子目录

### ISSUE THREAD

**Issue by Doekin** [tboox/tbox#270]
### 你在什么场景下需要该功能？

当文件结构如下时
```
.
└── ParentDir
    └── SubDir
```
调用`tb_directory_copy("./ParentDir", "./ParentDir/SubDir",TB_FILE_COPY_NONE)` ，会 coredump，并产生 `ParentDir/SubDir/SubDir/SubDir/SubDir/SubDir/...` 的结构

### 描述可能的解决方案

当路径参数有问题，会形成循环时，`tb_directory_copy` 返回 false

**Comment by waruqi** [comment]
这种你自己在外面检测下就好了，这边只提供最基础的跨平台实现，有些复杂的参数有效性检测，你外面自己也能做。。

**Comment by Doekin** [comment]
OK
