### ISSUE TITLE
[FEATURE REQUEST] Autotools support

### ISSUE THREAD

**Issue by silvioprog** [tboox/tbox#31]
Hello masters,

It would be nice to compile tbox with this magic incantation:

```bash
./configure
make
sudo make install
```

WDYT? :-)

**Comment by waruqi** [comment]
Not going to support it and I don't feel like it.

You can run only one command: 

```bash
$ make
```

It will install xmake and build tbox project automatically.

Or you can see the [document](http://xmake.io/#/home?id=installation) to  install xmake and build it.

```lua
$ xmake
```

**Comment by silvioprog** [comment]
Really it worked like a charm and generated the libraries. Thanks!
