### ISSUE TITLE
关于demo的sleep.c请教

### ISSUE THREAD

**Issue by xzzh999** [tboox/tbox#34]
你好，大牛，tbox的demo源码的sleep.c执行后开始打印了：

     [demo]: [coroutine: 10]: count: 9, interval: 10 ms
     [demo]: [coroutine: 1000]: count: 9, interval: 10 ms
     [demo]: [coroutine: 2000]: count: 9, interval: 10 ms
     [demo]: [coroutine: 100]: count: 9, interval: 10 ms
     ...

  我刚开始接触协程请见谅，有个地方想不通：按我的理解遇到 tb_msleep 后协程切出去了，10 ms超时后其它的协程(100, 1000, 2000 )应该不会执行啊，不应该是  tb_msleep 到时间后才会往后走麽？

**Comment by waruqi** [comment]
@xzzh999 那个demo是个while loop，`tb_msleep(10)`执行完，打印trace后，就进入下一次`tb_msleep(10)`了，这个时候其他协程就会执行，也就会打印出来。

**Comment by waruqi** [comment]
@xzzh999 你好，这里确实有些bug，因为里面针对时间戳进行了缓存优化，初始化的时候存在一些bug，现已修复，你可以尝试更新到master版本，再试下。

**Comment by xzzh999** [comment]
@waruqi 
好的，谢谢~

**Comment by skyformat99** [comment]
大牛牛，看了很多协程库，但是还是没有太搞清楚什么场景下使用？
比如，现在有10万台设备需要采集数据，采集的数据通过sql写入数据库。
如何用协程库来实现呢？谢谢。
还是说，用多个线程，每个线程上再跑协程库了？

**Comment by waruqi** [comment]
@skyformat99 你可以一个线程上去创建多个协程来调度同时写数据库，也可以多个线程。不过写数据库 需要hook底层的io接口，去切换调度，tbox暂时不支持hook操作，你可以找找其他一些协程库来实现。

你可以网上看一些关于协程的使用场景和介绍。。

**Comment by skyformat99** [comment]
谢谢解答。
目前来看确实最花费时间的情况是写入数据库。

**Comment by waruqi** [comment]
不客气

**Comment by xzzh999** [comment]
master 现在测试是正常的，关闭问题。
