### ISSUE TITLE
some errors occurred then run with vs2017 

### ISSUE THREAD

**Issue by tangaoo** [tboox/tbox#36]
错误	LNK2019	无法解析的外部符号 _in6addr_any，该符号在函数 _tb_sockaddr_load 中被引用

**Comment by waruqi** [comment]
@tangaoo 请在vs里面 链接下 ws2_32.lib .

**Comment by tangaoo** [comment]
问题已解决，谢谢~
添加`#pragma comment(lib, "Ws2_32.lib")`
