### ISSUE TITLE
tbox  在vs2017下 x86 无法编译通过

### ISSUE THREAD

**Issue by supermario1990** [tboox/tbox#37]
1、我使用 xmake project -k vs2017 -m "debug,release" 生产vs2017工程，发现只有x64能编译过，x86不能编译通过。
2、在windows下，用xmake 编译 tbox，release 的demo编译不过，dubug可以过。
3、在windows下，用xmake编译生产  x86 的静态库lib，我在使用的lib的时候，报“无法解析的外部符号 _in6addr_any”，是配置哪里不对吗？

**Comment by waruqi** [comment]
> 1、我使用 xmake project -k vs2017 -m "debug,release" 生产vs2017工程，发现只有x64能编译过，x86不能编译通过。

也有可能你这x64的系统环境，没有x86的lib库，导致链接不过？ 具体报什么错？

> 2、在windows下，用xmake 编译 tbox，release 的demo编译不过，dubug可以过。

什么编译错误？如果check.c那个编译错误，可以根据提示 自己改下代码，可能是vs2017编译严格了，对一些越界问题，编译期就检测到，提示警告，然后warn as error了，如果是这个问题，我之后会改下的。

> 3、在windows下，用xmake编译生产 x86 的静态库lib，我在使用的lib的时候，报“无法解析的外部符号 _in6addr_any”，是配置哪里不对吗？

需要连接下 `ws2_32.lib` ，你可以尝试在 vs 里面手动加一下试试

**Comment by waruqi** [comment]
> 2. demo编译不过

这个我刚修了下，可以更新master代码再试下。

**Comment by supermario1990** [comment]
> 1、我使用 xmake project -k vs2017 -m "debug,release" 生产vs2017工程，发现只有x64能编译过，x86不能编译通过。

 我的环境是win7 64，应该是有x86的lib库，之前写的程序都是x86的。
x86下报错：“ 无法从“tb_pointer_t”转换为“tb_byte_t *”   memset.c    第66行。我自己改了强制转换了下类型，发现又有其他错。所以请教下您了。 第3个问题，解决了。第2个问题我马上更新代码试试。

**Comment by waruqi** [comment]
> x86下报错：“ 无法从“tb_pointer_t”转换为“tb_byte_t *” memset.c 第66行。我自己改了强制转换了下类型，发现又有其他错。所以请教下您了。

应该是x86下没检测到vs自己的memset接口，导致编译使用tbox内置的实现了，这块可能有些强转的警告问题，你可以在xmake.lua里面 把 `set_warning()` 那行去掉重新生成下工程，或者在vs里面，把警告级别 降低下，出现警告不作为error 处理
