### ISSUE TITLE
好多的功能都没有实现啊!

### ISSUE THREAD

**Issue by xietong95** [tboox/tbox#38]

**Comment by xietong95** [comment]
读写部分

**Comment by waruqi** [comment]
有各种io读写支持啊，你是指哪些读写功能呢？

**Comment by xietong95** [comment]
不好意思,之前是我看错了.

**Comment by lc-soft** [comment]
有问题就好好描述清楚，遇到什么问题，有什么需求，适用于哪些场景，期望有什么结果，有哪些现有的例子可参考，这些最好都描述出来。这不是日常留言聊天，不要让别人花太多时间去研究你提的问题到底是什么。
