### ISSUE TITLE
协程bug?

### ISSUE THREAD

**Issue by bigbao9494** [tboox/tbox#39]
只创建一个协程如下：
static tb_void_t tb_demo_coroutine_echo(tb_cpointer_t priv)
{
	tb_co_channel_ref_t channel = tb_co_channel_init(0, tb_null, 0);
	tb_co_channel_send(channel, (tb_cpointer_t)1);
	return ;
}
程序结束时会出现断言失败
tb_co_scheduler_exit函数中 tb_assert(!tb_list_entry_size(&scheduler->coroutines_suspend));
原因是tb_co_channel_send  --> tb_co_scheduler_suspend中：switch to the original coroutine 
--> tb_co_scheduler_switch --> 
回到了tb_co_scheduler_loop中，而tb_list_entry_size==0，因为唯一的一个协程已经移到了scheduler->coroutines_suspend中去

**Comment by waruqi** [comment]
send 了之后 那个协程被挂起 其实还没有 完全结束。。需要其他协程resume 完成。。所有协程全部调度完才行，但是确已经执行了 scheher exit。。这个还不应该被执行的。。

这个应该是 用户协程使用上的问题。。用户需要自己控制 每个协程的正常调度。。例如你channel send了。。必须自己保证其他协程 有匹配的 channel recv 。。保证不会有残留协程。。在那边永久suspend

当然 tb_co_scheduler_loop 上也有点问题。这种情况 tb_co_scheduler_loop 不应该直接返回。。应该要一直等待下去。。直到所有 suspend处理完毕，这块我之后改进下

**Comment by codehz** [comment]
@waruqi 
永久suspend的时候是不是可以做成golang那样的deadlock检测，其实我觉得崩溃的行为更好一点。。。

**Comment by waruqi** [comment]
恩 这块后续会做些改进
