### ISSUE TITLE
IO处理和协程调度问题

### ISSUE THREAD

**Issue by bigbao9494** [tboox/tbox#40]
tb_co_scheduler_io_loop中只有当scheduler->coroutines_ready没有协程时才会去调用tb_poller_wait处理IO事件，也就是所有的协程都阻塞在IO或sleep时才查看socket上是否可读可写，通过tb_co_scheduler_yield来往其它活动协程切换的。这种做法如果有两个协程一直自在活动中，它们没有调用阻塞和sleep，那这样网络事件将没有机会处理？？

**Comment by waruqi** [comment]
这就跟 n个线程，有两个线程一直在那死循环处理，不wait把cpu占满，其他线程得不到执行一个道理，这个应该是开发者写多线程/协程时候，自己需要控制的逻辑。。。

**Comment by bigbao9494** [comment]
是这样的：
用户协程1，2  业务逻辑会有网络数据收发
用户协程3，4  业务逻辑仅仅是一些计算只占用CPU资源，它们不会阻塞，{compute;tb_coroutine_yield();}
使用者本来是想让所有的协程都会有机会执行，1和2有数据时也能处理没有数据时不管，可能3和4会一直工作

**Comment by waruqi** [comment]
就算调度器 让所有协程都有机会执行，如果3, 4在短期内 一直没数据，就算给他们机会去 wait poll了下，发现没数据立即返回，相当于3, 4还是会在那边不停地来回yield 狂转cpu 哈。。

就跟四个线程，两个在那里wait，一直没数据过来时一直在哪里挂起着，另外两个线程 还是在那不停 死循环 把cpu占满这，就算这个时候 网络上有数据过来了，另外两个io线程一样没多少机会执行。。

**Comment by bigbao9494** [comment]
另外两个线程还是有机会执行的，CPU始终还是会切换到这两个线程。
但是我们现在的问题是有数据来了，这两个协程永远都没有机会执行呢。
现在的设计应该可以叫做抢占式系统，runable抢占io_wait

**Comment by waruqi** [comment]
> 另外两个io线程一样没多少机会执行。。

恩 我也说了 线程模式 没多少机会执行，也就是说多少是有点机会被执行到，但是其他两个线程在那一点wait都没有的不停的来回yield，把cpu跑满，这逻辑本身也是不对的。。

**Comment by bigbao9494** [comment]
明白了
