### ISSUE TITLE
uClibc库支持吗？

### ISSUE THREAD

**Issue by wgpqys** [tboox/tbox#44]
请问在嵌入式设备的uClibc上，tbox的所有功能能过吗？

**Comment by waruqi** [comment]
tbox内置轻量libc实现，也会去自动检测当前编译环境自带libc的部分接口是否存在，如果存在就优先使用，不存在的libc接口，才会切到自带的轻量实现上去。。

所以不依赖特定某个libc库，就算没有libc库，也能完全正常运行
