### ISSUE TITLE
More efficient coroutine implementation

### ISSUE THREAD

**Issue by Cheedoong** [tboox/tbox#48]
Check if this one could be helpful: 
https://www.oschina.net/p/libaco

**Comment by waruqi** [comment]
Ok, I will see it.

**Comment by waruqi** [comment]
I tested it and found that libaco is no faster than the tbox's coroutine.

The benchmark test result on my machine:

```
tbox: 10000000 switches in 282 ms, 35460992 switches per second
libaco: 10000000 switches in 429 ms, 23310023 switches per second
go: 10000000 switches in 1162 ms, 8605851 switches per second
```

My machine: `Linux ruki 4.13.0-25-generic #29-Ubuntu SMP Mon Jan 8 21:14:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

If you want to known more, you can see [benchbox](https://github.com/tboox/benchbox), I have added  libaco test code.
