### ISSUE TITLE
错误:总是创建链表失败

### ISSUE THREAD

**Issue by yangjz1125** [tboox/tbox#52]
在我的计算机上, tb_list_init总是返回NULL。
`int main(){
tb_list_ref_t a = tb_list_init(0, tb_element_long());
	printf("over\n");
	if(a == NULL){
		printf("NULL\n");
		return 0;
	}
tb_list_exit(a);
}`
输出
over
NULL
我使用UBUNTU 18.04 LTS

**Comment by waruqi** [comment]
你没有初始化tbox库，得先调用下 tb_init 在demo.c里面 你可以看下

**Comment by yangjz1125** [comment]
谢谢。我这次创建成功了。
