### ISSUE TITLE
链接错误

### ISSUE THREAD

**Issue by yangjz1125** [tboox/tbox#55]
我在编译出来的库中，找不到关于`utils/option`的函数，也没有编译其对应的`demo`。
也许`option`被废除了，但是我找不到任何与之对应的标记或说明。
也许是`xmake.lua`中有一些错误：将`add_files("utils/*.c|option.c")`改为`add_files("utils/*.c|utils/option.c")`后可以正常编译`option`但出现更多依赖。

**Comment by waruqi** [comment]
option依赖object扩展模块，而tbox默认编译是small模式编译，就是禁用所有扩展模块，只要启用object来编译，就可以正常使用option了。。

```console
$ xmake f --object=y
$ xmake
```
> 也许是xmake.lua中有一些错误：将add_files("utils/*.c|option.c")改为add_files("utils/*.c|utils/option.c")后可以正常编译option但出现更多依赖。

此处`add_files("utils/*.c|option.c")`意思就是添加除option.c以外的所有utils下源文件，因为option.c在后面会根据object条件启用：

```lua
    if is_option("object") then
        add_files("utils/option.c")
        add_files("object/*.c")
    end
```

**Comment by yangjz1125** [comment]
谢谢，麻烦了。
