### ISSUE TITLE
tb_socket_ctrl支持更多参数

### ISSUE THREAD

**Issue by sharpbai** [tboox/tbox#66]
我正在把一个基于tcp的阻塞式传输库搬到tbox的协程上来，发现socket参数有些配置是没有的。如:

KeepAlive类
- SOL_SOCKET SO_KEEPALIVE
- IPPROTO_TCP TCP_KEEPINTVL

```
int keepalive = 1;
        setsockopt(r->m_sb.sb_socket, SOL_SOCKET, SO_KEEPALIVE, (void *) (&keepalive), (socklen_t) sizeof(keepalive));
        int keepalive_intvl = 5;
        setsockopt(r->m_sb.sb_socket, IPPROTO_TCP, TCP_KEEPINTVL, (void *) (&keepalive_intvl),
                   (socklen_t) sizeof(keepalive_intvl));
```

忽略SIGPIPE事件
- SOL_SOCKET SO_NOSIGPIPE

```
        int value = 1;
        int ret = setsockopt(r->m_sb.sb_socket, SOL_SOCKET, SO_NOSIGPIPE, &value, sizeof(value));
```
请问可否提交相关代码加上相关设置

**Comment by waruqi** [comment]
你可以提个pr来支持这些，具体请看下：https://github.com/tboox/tbox/blob/master/CONTRIBUTING.md

不过提交的socket设置，需要考虑跨平台支持，windows等其他平台也需要有相关设置实现，如果有些平台暂时不支持的设置，可以返回-1

**Comment by waruqi** [comment]
这些我都加上了，如果有其他设置 可以提pr
