### ISSUE TITLE
如何快速优雅地停止协程 scheduler ？

### ISSUE THREAD

**Issue by kwhitestone** [tboox/tbox#67]
以 echo_server 为例子， 假如有许多客户端(例如5万个) 连接着， 那么有上万个协程会处于 tb_socket_wait  这一等待中， 发送什么信号可以它们同时快速地退出 ， 并使 scheduler 安全退出？

**Comment by kwhitestone** [comment]
假如对所有的socket进行close调用 ， 那scheduler也需要等所有协程都退出才能安全地调用 tb_co_scheduler_exit 。那是否需要使用者自己做信号量， 等待所有的协程都完全退出 ？

**Comment by waruqi** [comment]
可以试试 tb_co_scheduler_kill ，这个会触发一个通知让epoll/select wait 提前返回，然后取消所有timer中的wait task，执行kill后，scheduler loop 应该会自动快速结束，然后在安全调用下 tb_co_scheduler_exit 试试

不过这个接口，我一般不怎么用，所以没怎么详细测过，如果有问题可以跟我反馈
