### ISSUE TITLE
tbox的网络模块，有没有计划支持socks4 socks5 http代理？

### ISSUE THREAD

**Issue by totalwei** [tboox/tbox#72]
tbox的网络模块，有没有计划支持socks4 socks5 http代理？

**Comment by waruqi** [comment]
暂时不考虑支持，tbox的定位是跨平台基础库，已跨平台为主，提供基础可用模块，消除平台的差异性。

更多的协议层，应用层支持，我会考虑新建独立网络库去提供，不过短期内没这计划。
