### ISSUE TITLE
更新代码之后，没有生成对应的头文件

### ISSUE THREAD

**Issue by veryitman** [tboox/tbox#84]
更新到最新代码之后，xmake 编译后没有生成对应的头文件，是需要额外操作吗？

**Comment by waruqi** [comment]
新版本我去掉了，构建时候copy所有头文件，影响编译效率。如果需要获取头文件可以通过下面两种方式：

1. 通过xmake p/xmake package命名导出build/tbox.pkg包，里面有全plat/arch的所有库以及对应头文件，目录结构分类组织好的，方便管理，也可以直接在xmake.lua中通过 add_packages方式，直接引用tbox.pkg包

2. 通过xmake i/xmake install安装导出对应库和头文件，你可以指定导出到其他目录中

```console
$ xmake install -o /home/xxx
```

**Comment by veryitman** [comment]
@waruqi 最好能在 Readme 里面说明。

**Comment by waruqi** [comment]
头文件这块，跟其他构建工具，例如make/autoconf/cmake都是行为都是类似的，只需要make/make install就行了

目前还没时间更新readme 以及文档支持。。你先自己摸索下吧，有问题可以提issues。。

之后有时间我会更新说明下的。

**Comment by veryitman** [comment]
@waruqi 用你的方法可以的，感谢指导！
