### ISSUE TITLE
平台库能否增加timerfd eventfd等linux特有的fd

### ISSUE THREAD

**Issue by codehz** [tboox/tbox#85]
如题，虽然是linux特有，但是glibc都有所封装（具体就是timerfd可以把计时器转为文件读取，eventfd可以用于跨线程投递事件，signalfd可以把信号处理转为文件读取，均支持select poll epoll等操作

**Comment by waruqi** [comment]
暂时不会考虑 tbox的目的就是为了尽量消除平台差异性，在写上层代码的时候，用户不需要再去#if IS_LINUX判断，来处理各种逻辑

tbox的poller除了epoll poll等，还同时支持win iocp，上层接口完全一致。。因此不会考虑暴露这些，这也违背了我写tbox的初衷

如果你需要这些，可直接include linux下相关库，来操作，也就没必要用tbox了
