### ISSUE TITLE
Coroutine assembly code for bitcode

### ISSUE THREAD

**Issue by L1MeN9Yu** [tboox/tbox#91]
目前协程中的汇编正常情况下不支持编译成bitcode,但是发现阿里的coobjc里的是支持的.代码链接: https://github.com/alibaba/coobjc/blob/master/cocore/coroutine_context.s
看到他对齐都是2,也没有用什么STL以外的东西,个人猜测是编译时候做了内联?
个人能力有限,目前还不知道如何做到😂.
不知未来有支持的打算吗?

**Comment by waruqi** [comment]
嗯，我下个版本更新的时候，会支持下这块

**Comment by waruqi** [comment]
我试了下，编译bitcode的iphoneos版本没啥问题，ok啊。

你这报啥错？

**Comment by L1MeN9Yu** [comment]
```
xmake f --hash=y --zip=y --coroutine=y --exception=y --object=y --xml=y --charset=y -p iphoneos -a arm64 --target_minver=9 --cxflags="-fembed-bitcode" --mxflags="-fembed-bitcode"
```
![image](https://user-images.githubusercontent.com/6925196/56178156-c66ad700-6033-11e9-861b-31908fa92f80.png)

**Comment by waruqi** [comment]
那是因为 你没加 `--asflags="-fembed-bitcode"` 对汇编代码启用bitcode，你只设置了c/c++/objc/objc++代码的bitcode启用。

**Comment by L1MeN9Yu** [comment]
😂
Soved.
