### ISSUE TITLE
xmake cannot find known tool script问题

### ISSUE THREAD

**Issue by hixixTech** [tboox/tbox#93]
1、工具链目录：
![image](https://user-images.githubusercontent.com/9931868/58632474-1c5fb980-8318-11e9-9383-2a1e68bce2cd.png)

2、在tbox目录中执行命令
david@ubuntu:~/ubuntu_share/tbox.git$ xmake f -p linux --sdk=/home/david/ubuntu_share/EC20CEFAGR06A05M4G_OCPU_SDK/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/ --bin=/home/david/ubuntu_share/EC20CEFAGR06A05M4G_OCPU_SDK/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/arm-oe-linux-gnueabi --cross=arm-oe-linux-gnueabi- -v
configure
{
    deprecated = false
    polarssl = false
    small = true
    arch = none
    sqlite3 = false
    info = false
    cc = /home/david/ubuntu_share/EC20CEFAGR06A05M4G_OCPU_SDK/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/arm-oe-linux-gnueabi/arm-oe-linux-gnueabi-gcc  -march=armv7-a -mfloat-abi=softfp -mfpu=neon
    cross = arm-oe-linux-gnueabi-
    plat = linux
    sdk = /home/david/ubuntu_share/EC20CEFAGR06A05M4G_OCPU_SDK/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/
    wchar = false
    float = true
    ndk_stdcxx = true
    host = linux
    xml = false
    bin = /home/david/ubuntu_share/EC20CEFAGR06A05M4G_OCPU_SDK/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/arm-oe-linux-gnueabi
    exception = false
    openssl = false
    zlib = false
    regex = false
    coroutine = false
    pcre = false
    mysql = false
    mode = release
    ccache = true
    database = false
    zip = false
    pcre2 = false
    hash = false
    micro = false
    mbedtls = false
    buildir = build
    object = false
    charset = false
    demo = true
    kind = static
}

3、再在执行xmake
![image](https://user-images.githubusercontent.com/9931868/58632558-72ccf800-8318-11e9-9666-356f48206372.png)

出错，提示配置b不对。
从-v参数看，设置都是正确。

**Comment by waruqi** [comment]
我看 配置里面  CC 编译器 居然是  `cc = /home/david/ubuntu_share/EC20CEFAGR06A05M4G_OCPU_SDK/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/arm-oe-linux-gnueabi/arm-oe-linux-gnueabi-gcc -march=armv7-a -mfloat-abi=softfp -mfpu=neon`

后面怎么会有 `-march=armv7-a -mfloat-abi=softfp -mfpu=neon` ，我看你这配置里面也没加这些。。

你在执行 `xmake f `的时候，追加一下 `-c` 参数，强制清下配置缓存，重新检测下编译器试试：

```console
xmake f -p linux --sdk=/home/david/ubuntu_share/EC20CEFAGR06A05M4G_OCPU_SDK/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/ --bin=/home/david/ubuntu_share/EC20CEFAGR06A05M4G_OCPU_SDK/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/arm-oe-linux-gnueabi --cross=arm-oe-linux-gnueabi- -v -c
```

**Comment by hixixTech** [comment]
多谢。解决了。

xmake很棒，很好用！
