### ISSUE TITLE
新建工程的xmake问题

### ISSUE THREAD

**Issue by hixixTech** [tboox/tbox#94]
1、新建空的工程
![image](https://user-images.githubusercontent.com/9931868/58745464-f35c3780-8483-11e9-8f04-cfbf1d420c1e.png)

2、在新建的工程目录TEST-APP中
david@ubuntu:~/ubuntu_share/tbox.linux.x86/TEST-APP$ xmake f -p linux --sdk=/home/david/ubuntu_share/EC20CEFAGR06A05M4G_OCPU_SDK/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/ --bin=/home/david/ubuntu_share/EC20CEFAGR06A05M4G_OCPU_SDK/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/arm-oe-linux-gnueabi --cross=arm-oe-linux-gnueabi- -v -c

3、执行xmake
david@ubuntu:~/ubuntu_share/tbox.linux.x86/TEST-APP$ xmake -v
configure
{
    ccache = true
    mode = release
    ndk_stdcxx = true
    host = linux
    cc = /usr/bin/gcc
    kind = static
    buildir = build
    plat = linux
    ld = /usr/bin/g++
    arch = x86_64
}
看到的还是使用 /usr/bin/gcc，而不是设置的交叉编译工具链。
tbox工程目录的xmake.conf确正确的设置为了交叉编译工具链。

这要如何设置？

**Comment by waruqi** [comment]
你重新更新下2.2.6版本 之前有个bug

**Comment by hixixTech** [comment]
更新了。
问题还是一样的......
手动修改了新建工程中的 ".xmake\linux\x86_64\xmake.conf"，再“xmake -v”会出现 xmake.conf 找不到的错误。

**Comment by waruqi** [comment]
加-v给下完整编译输出

```console
xmake f -p linux --sdk=/home/david/ubuntu_share/EC20CEFAGR06A05M4G_OCPU_SDK/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/ --bin=/home/david/ubuntu_share/EC20CEFAGR06A05M4G_OCPU_SDK/ql-ol-sdk/ql-ol-crosstool/sysroots/x86_64-oesdk-linux/usr/bin/arm-oe-linux-gnueabi --cross=arm-oe-linux-gnueabi- -v -c
xmake -r -v
```

**Comment by waruqi** [comment]
你这个看着就像是2.2.6版本之前的那个问题：https://github.com/xmake-io/xmake/issues/427

你更新到dev分支试试呢？
