### ISSUE TITLE
tcp client的问题请教

### ISSUE THREAD

**Issue by hixixTech** [tboox/tbox#95]
为测试tcp client的用法，写了一下例子：
`/* //////////////////////////////////////////////////////////////////////////////////////
 * includes
 */
#include "../demo.h"

#define TEST_SERVER_ADDR             "192.168.10.30"
#define TEST_SERVER_PORT             9001
#define TEST_DEMO_TIMEOUT            -1

#define TCP_CLIENT_MAX_SZ            3
#define TCP_CLIENT_DATA_BUF_SZ       8192

// the client type
typedef struct __tb_demo_tcp_client_t
{
	// the event
    tb_event_ref_t      event;
	tb_thread_ref_t     thread;
    // the client socket
    tb_socket_ref_t     sock;
    // the address
    tb_ipaddr_t         addr;
    // the data buffer
    tb_byte_t           data[TCP_CLIENT_DATA_BUF_SZ];
    // the recv size
    tb_hize_t           recv;
    // the real size
    tb_long_t           real;
    // the wait state
    tb_long_t           wait;
    // the time
    tb_hong_t           time;
    // connect ok?
    tb_long_t           ok;
	// is stoped?
    tb_atomic_t         bstoped;
	// the index
    tb_size_t           index;
}tb_demo_tcp_client_t, *tb_demo_tcp_client_ref_t;

tb_demo_tcp_client_t _client[TCP_CLIENT_MAX_SZ];

static tb_int_t tcp_client_rcv_thread_func(tb_cpointer_t priv)
{
	tb_demo_tcp_client_t* _pclient = (tb_demo_tcp_client_t*)priv;

    // trace
    tb_trace_i("[%p]: recving ..", _pclient->sock);

    // recv data
    tb_byte_t data[TCP_CLIENT_DATA_BUF_SZ];
    tb_hize_t recv = 0;
    tb_long_t wait = 0;
    tb_hong_t time = tb_mclock();
    while (!tb_atomic_get(&_pclient->bstoped)){
    //while (1){
        // read it
        tb_long_t real = tb_socket_recv(_pclient->sock, data, sizeof(data));
        // trace
        tb_trace_d("[%p]: recv: %ld, total: %lu", _pclient->sock, real, recv + (real > 0? real : 0));

        // has data?
        if (real > 0){
            recv += real;
            wait = 0;
        }else if (!real && !wait){// no data? wait it
            // wait it
            wait = tb_socket_wait(_pclient->sock, TB_SOCKET_EVENT_RECV, TEST_DEMO_TIMEOUT);
        }else{// failed or end?
        	tb_trace_i("[%p]: network disconnection is happen...", _pclient->sock, &_pclient->addr);
        	break;
        }

		// trace
    	tb_trace_i("[%p]: recv %llu bytes %lld ms", _pclient->sock, recv, tb_mclock() - time);
    }

    // exit socket
    if (_pclient->sock) 
		tb_socket_exit(_pclient->sock);
    _pclient->sock = tb_null;

	//tb_atomic_set(&_pclient->bstoped, 1);

	tb_trace_i("[%p]: client recv thread exit...", _pclient->sock);
	
    // ok
    return 0;
}

static tb_int_t connect_to_server(tb_byte_t n, const tb_char_t* addr, tb_uint16_t port)
{
	tb_int_t rtn = 0;

	_client[n].event = tb_event_init();
	tb_event_post(_client[n].event);
	// init index
    _client[n].index = n;

    // init stoped
    _client[n].bstoped = 0;
	
	// init socket
    _client[n].sock = tb_socket_init(TB_SOCKET_TYPE_TCP, TB_IPADDR_FAMILY_IPV4);

    // init address
    tb_ipaddr_set(&_client[n].addr, addr, port, TB_IPADDR_FAMILY_IPV4);

    // trace
    tb_trace_i("[%p]: connecting %{ipaddr} ..", _client[n].sock, &_client[n].addr);

    // connect socket
    while (!(_client[n].ok = tb_socket_connect(_client[n].sock, &_client[n].addr))){
		// wait it
        if (tb_socket_wait(_client[n].sock, TB_SOCKET_EVENT_CONN, TEST_DEMO_TIMEOUT) <= 0){
			break;
        }
    }

	if (_client[n].ok <= 0)
		rtn = -1;

	return rtn;
}

static tb_int_t tcp_client_wait_exit_thread_func(tb_cpointer_t priv)
{
	tb_demo_tcp_client_t* _pclient = (tb_demo_tcp_client_t*)priv;
	
	tb_trace_i("wait thread[%d] exter...", _pclient->index);
	while (!tb_atomic_get(&_pclient->bstoped)){
		if (!tb_thread_wait(_pclient->thread, 5000, tb_null)){
		    tb_trace_i("wait thread[%d]: timeout", _pclient->index);
		}
			
		//tb_thread_exit(_client_thread[*i]);
	}
	tb_trace_i("wait thread[%d] exit...", _pclient->index);

	return 0;
}

/* //////////////////////////////////////////////////////////////////////////////////////
 * main
 */ 
tb_int_t tb_demo_tcp_client_main(tb_int_t argc, tb_char_t** argv)
{
	tb_byte_t i = 0;
	int n = 0;

	while (1){
		n = getchar();
		if (n == 'c'){
			for (i = 0; i < TCP_CLIENT_MAX_SZ; i++){
			    if (-1 == connect_to_server(i, TEST_SERVER_ADDR, TEST_SERVER_PORT)){
					tb_trace_i("connecting server %{ipaddr} failed...",  &_client[i].addr);
			    }else{
					_client[i].thread = tb_thread_init(tb_null, tcp_client_rcv_thread_func, &_client[i], 0);
					tb_thread_init(tb_null, tcp_client_wait_exit_thread_func, &_client[i], 0);
			    }
			}
		}else if (n == '0'){
			tb_atomic_set(&_client[0].bstoped, 1);
			tb_trace_i("tb_socket_exit [%d]...",  _client[0].sock);
			//if (_client[0].sock) 
			//	tb_socket_exit(_client[0].sock);
			//_client[0].sock = tb_null;
		}
	}

    return 0;
}
`
问题：
（1）输入0后，_client[0].sock没有退出；
![image](https://user-images.githubusercontent.com/9931868/58922457-825f9d00-876d-11e9-9b9b-b7ae0c52d62f.png)

（2）正在熟悉tbox库，请教下用哪个API能正确的退出所选的client socket连接呢？

**Comment by waruqi** [comment]
tb_socket_exit仅用于io完全结束后 对 fd的资源释放，试下 tb_socket_kill

**Comment by hixixTech** [comment]
tb_socket_kill可以退出所选择的client socket，退出后还要再用tb_socket_exit释放资源吗？

**Comment by waruqi** [comment]
是的
