### ISSUE TITLE
编译出错   right shift count >= width of type

### ISSUE THREAD

**Issue by q962** [tboox/tbox#99]
mingw 64bit

MINGW64_NT-10.0-17134 XXX 3.0.7-338.x86_64 2019-07-11 10:58 UTC x86_64 Msys

- xmake.exe f -p mingw
- xmake.exe build

```
error: src\tbox\memory\../utils/bits.h:639:26: error: right shift count >= width of type [-Werror=shift-count-overflow]
  639 |     p[4] = (tb_byte_t)(x >> 32);
      |                          ^~
src\tbox\memory\../utils/bits.h:640:26: error: right shift count >= width of type [-Werror=shift-count-overflow]
  640 |     p[5] = (tb_byte_t)(x >> 40);
      |                          ^~
src\tbox\memory\../utils/bits.h:641:26: error: right shift count >= width of type [-Werror=shift-count-overflow]
  641 |     p[6] = (tb_byte_t)(x >> 48);
      |                          ^~
src\tbox\memory\../utils/bits.h:642:26: error: right shift count >= width of type [-Werror=shift-count-overflow]
  642 |     p[7] = (tb_byte_t)(x >> 56);
      |                          ^~
src\tbox\memory\../utils/bits.h: In function 'tb_bits_set_u64_be_inline':
src\tbox\memory\../utils/bits.h:646:26: error: right shift count >= width of type [-Werror=shift-count-overflow]
  646 |     p[0] = (tb_byte_t)(x >> 56);
      |                          ^~
src\tbox\memory\../utils/bits.h:647:26: error: right shift count >= width of type [-Werror=shift-count-overflow]
```

 根据  `x >> 32` 断定  tb_uint64_t == ulong

```c
#if defined(TB_COMPILER_IS_MSVC)
typedef __int64                     tb_int64_t;
typedef unsigned __int64            tb_uint64_t;
#elif (TB_CPU_BITSIZE == 64)
typedef signed long                 tb_int64_t;
typedef unsigned long               tb_uint64_t;
#else
typedef signed long long            tb_int64_t;
typedef unsigned long long          tb_uint64_t;
#endif
```
在本机上 sizeof(ulong) == 4

至少在本机上 TB_CPU_BITSIZE  并不能作为 long 宽度的判断方法

**Comment by waruqi** [comment]
目前这边只对msvc/x64上做了处理。所以 mingw/x64 for windows的环境没测过。暂时也没环境测试。

https://github.com/tboox/tbox/blob/3f50a7cb910802f4412b8c2de5173327a77e3d3c/src/tbox/prefix/type.h#L127-L133

你可以临时改下这块试试，探测下 mingw/x64 for windows的环境，也对tb_long_t处理成int64。。如果ok，可以提个pr到dev分支。

**Comment by q962** [comment]
>所以tbox里面不使用原生long的， 为了规范化long，tbox里面统一按 x64 -> int64 ， x86 -> int32 来设置long的。。tb_size_t/tb_long_t 都是如此，方便跨平台代码一致性。

了解目的，那么是通过什么方法知道基本变量的宽度的呢

https://github.com/tboox/tbox/blob/d887e4ef6ca2eb225d64398f1b27ad3dd9415414/src/tbox/prefix/type.h#L110-L120

这里是通过编译器和 cpu 位数来判断

为什么要通过cpu位数来判断？ 宽度和 cpu 位数相关？ 

`stdint.h` 不具有可移植性？

在 MSVC 下可以使用 __int64，那么 long 的宽度呢，

如果宽度和cpu位数相关，那么宽度对于各大编译器来说是一样长的，
所以可以通过编写一个程序来获得所有宽度，方法可取吗？

但是如果和编译器相关，那么我觉得很麻烦，需要适配所有的编译器(我觉得不可能)

---

> 除了在传递到win api的时候，会强制到原生LONG，通常情况内部通用代码都是采用的tb_long_t/tb_size_t，保持跟cpu bits size一致

不太懂什么意思 😂

**Comment by waruqi** [comment]
> 了解目的，那么是通过什么方法知道基本变量的宽度的呢

刚说了，tbox里面不用原生的long，而是tb_long_t，内部规范约定了宽度，不需要判断 64bits cpu 必须用int64

> 这里是通过编译器和 cpu 位数来判断
> 
> 为什么要通过cpu位数来判断？ 宽度和 cpu 位数相关？

可以不用判断，当初早期只考虑到msvc下long才具有特殊性，其他平台我默认long根据cpu width匹配了，所以优先用了这个，这块可以改进，直接采用 long long 处理成int64也是可以的。

> 
> `stdint.h` 不具有可移植性？

很多构建环境连stdint.h都没有。。你说可移植么？ vs2008以前都没提供。

> 
> 在 MSVC 下可以使用 __int64，那么 long 的宽度呢，

msvc下 原生long是32bits

> 
> 如果宽度和cpu位数相关，那么宽度对于各大编译器来说是一样长的，
> 所以可以通过编写一个程序来获得所有宽度，方法可取吗？

通过编译器内置宏判断不就好了，还写程序动态获取？交叉编译的程序本机都运行不起来。

> 
> 但是如果和编译器相关，那么我觉得很麻烦，需要适配所有的编译器(我觉得不可能)

现在就是通过编译器内置宏适配，适配常用编译器环境就行了，无非就是msvc, gcc, clang以及交叉编译环境，顶多再加几个不常用的，也不需要一开始就适配全，我现在就是采取的延迟适配策略，遇到问题再去改进适配，就好比你现在的环境，遇到问题了，适配支持下 不就好了。。

实在不行，等回头有时间我装个mingw x64的环境，给你适配下就好了。。

> 不太懂什么意思 😂

这个你自己理解吧。

**Comment by q962** [comment]
> 刚说了，tbox里面不用原生的long，而是tb_long_t，内部规范约定了宽度，不需要判断， 64bits cpu 必须用int64，32bits cpu用int32

我并没有询问如何知道long(tb_long)的宽度，而是询问tb_intX 是如何确定的(我已经知道了)

首先我知道内置宏的存在

我之所以问问这么多是因为
https://github.com/tboox/tbox/blob/3f50a7cb910802f4412b8c2de5173327a77e3d3c/src/tbox/prefix/type.h#L101

已经使用了 __WCHAR_WIDTH__ ，那为什么不继续使用其他内置宏？而是通过cpu位数来判断(我已经知道为什么了)

> 实在不行，等回头有时间我装个mingw x64的环境，给你适配下就好了。。

安装mingw不应该是为了类型，而是为了适配xmake install
应该和适配msvc一样，适配gcc/clang


-----

说了这么多或许你已经不耐烦了

我发这个issue只是想知道已经使用内置宏，为什么不继续使用其他内置宏而是使用cpubit

**Comment by waruqi** [comment]
> 安装mingw不应该是为了类型，而是为了适配xmake install
> 应该和适配msvc一样，适配gcc/clang

没明白你的需求，要适配xmake install的什么场景？这跟mingw是什么关系？

> 我发这个issue只是想知道已经使用内置宏，为什么不继续使用其他内置宏而是使用cpubit

cpubit不也是通过内置宏判断的么？目前的场景cpubit来判断已基本可用，目前没啥问题，就没去通过其他宏判断，之前我也说了，如果后续遇到问题，比如你这的mingw x64环境，如果cpubit搞不定，可以继续通过其他内置宏做进一步判断改进

我可没说不能用其他内置宏判断，只是之前还没遇到非得用其他宏判断的场景

**Comment by q962** [comment]
我指的是
```c
__SCHAR_WIDTH__
__SHRT_WIDTH__
__INT_WIDTH__
__LONG_WIDTH__
__LONG_LONG_WIDTH__
__PTRDIFF_WIDTH__
__SIG_ATOMIC_WIDTH__
__SIZE_WIDTH__
__WCHAR_WIDTH__
__WINT_WIDTH__
__INT_LEAST8_WIDTH__
__INT_LEAST16_WIDTH__
__INT_LEAST32_WIDTH__
__INT_LEAST64_WIDTH__
__INT_FAST8_WIDTH__
__INT_FAST16_WIDTH__
__INT_FAST32_WIDTH__
__INT_FAST64_WIDTH__
__INTPTR_WIDTH__
__INTMAX_WIDTH__
```

我不知道 64bit cpu 和 long 宽的关联，但我知道 \_\_LONG_WIDTH\_\_ 和 long 宽有关联

**Comment by q962** [comment]
> 安装mingw不应该是为了类型，而是为了适配xmake install
应该和适配msvc一样，适配gcc/clang

哦，抱歉，错了，我理解成了 msys2 里的 mingw64

mingw64 路径和msys路径是不一样的，所以需要适配它

不管是 linux 还是 mingw 使用的或许是 gcc，那么 gcc 的指令都是一样的，所以不需要专门为了使用 mingw 下的 gcc 而去下载

**Comment by waruqi** [comment]
> 我不知道 64bit cpu 和 long 宽的关联，但我知道 __LONG_WIDTH__ 和 long 宽有关联

还是我之前说过的，我不管__LONG_WIDTH__ 还是 cpubits是否跟long有什么关联，tbox里面基本不用原生long，只用tb_long_t

而tb_long_t里面，我自己强制约定跟cpu bits强相关，所以不需要判断__LONG_WIDTH__

引用之前说的

> 所以tbox里面不使用原生long的， 为了规范化long，tbox里面统一按 x64 -> int64 ， x86 -> int32 来设置long的。。tb_size_t/tb_long_t 都是如此，方便跨平台代码一致性

**Comment by waruqi** [comment]
> > 安装mingw不应该是为了类型，而是为了适配xmake install
> > 应该和适配msvc一样，适配gcc/clang
> 
> 哦，抱歉，错了，我理解成了 msys2 里的 mingw64
> 
> mingw64 路径和msys路径是不一样的，所以需要适配它
> 
> 不管是 linux 还是 mingw 使用的或许是 gcc，那么 gcc 的指令都是一样的，所以不需要专门为了使用 mingw 下的 gcc 而去下载

还是不明白你要表达什么？

**Comment by q962** [comment]
```c
#if defined(TB_COMPILER_IS_MSVC)
typedef __int64                     tb_int64_t;
typedef unsigned __int64            tb_uint64_t;
#elif (TB_CPU_BITSIZE == 64)
typedef signed long                 tb_int64_t;     // 这个
typedef unsigned long               tb_uint64_t;
#else
typedef signed long long            tb_int64_t;
typedef unsigned long long          tb_uint64_t;
#endif
```

我一直在说 tb_int64_t ，因为上面的代码你使用了 long （我有区分 long ＆ tb_long），所以我一直在说 long

> 根据 x >> 32 断定 tb_uint64_t == ulong // 我一开始就明确指出了  tb_uint64_t

**Comment by waruqi** [comment]
int64这个 我之前不是已经说过了么

> 可以不用判断，当初早期只考虑到msvc下long才具有特殊性，其他平台我默认long根据cpu width匹配了，所以优先用了这个，这块可以改进，直接采用 long long 处理成int64也是可以的。

我说了 可以通过其他内置宏改进 为什么还要去纠结呢。。

**Comment by q962** [comment]
首先我并没有纠结

我可以使用内置宏通过编译，

> 我不知道 64bit cpu 和 long 宽的关联，但我知道 __LONG_WIDTH__ 和 long 宽有关联

这句话我不知道你是怎么你理解的，因为你使用 cpu 位数判断 long 的长度（不是 tb_long）
所以我就很好奇而已

而且这个答案你已经说了 

> 可以不用判断，当初早期只考虑到msvc下long才具有特殊性，__其他平台我 **默认** long根据cpu width匹配了__，所以优先用了这个，这块可以改进，直接采用 long long 处理成int64也是可以的。


所以至始至终我在想搞清楚cpu 位数和 long 的长度之间的关系， 见本回复的第一个引用

所以我现在已经知道你是怎么想的了

所以我并没有纠结

**Comment by waruqi** [comment]
> 这句话我不知道你是怎么你理解的，因为你使用 cpu 位数判断 long 的长度（不是 tb_long）
所以我就很好奇而已

> 而且这个答案你已经说了

这个答案 我是在第二次回复的时候 就已经说了的 所以不理解为什么后面还要问这个

**Comment by q962** [comment]
解释一下，不过太长了，也不用浪费无用的时间看了，我的时间不值钱

----
```


提问者1 ：  提出 tb_uint64_t  至少在本机上 TB_CPU_BITSIZE 并不能作为 long 宽度的判断方法

回答者2：  目前这边只对msvc/x64上做了处理。所以 mingw/x64 for
	windows的环境没测过。暂时也没环境测试。

	所以tbox里面不使用原生long的， 为了规范化long，	tbox里面统一按 x64 -> int64 ， x86 -> int32 来设置long的。。tb_size_t/tb_long_t 都是如此，	 方便跨平台代码一致性。

	//*/*/  回答long 的事情，这个 long 和 int64 相关，并不是想了解 long 
	/*/*/*  的宽度，只是因为你将 long 作为 int64 的原始类型而已

提问者3： 
	为什么要通过cpu位数来判断？ 宽度和 cpu 位数相关？
	
	/*/*/* 询问

	如果宽度和cpu位数相关，那么宽度对于各大编译器来说是一样长的，
	所以可以通过编写一个程序来获得所有宽度，方法可取吗？
	
	/*//*/** 没考虑交叉编译，我目前不可能遇到相关问题，所以不可能想到交叉编译的事情
	
回答者4：
	刚说了，tbox里面不用原生的long，而是tb_long_t，内部规范约定了宽度，不需要判断， 64bits cpu 必须用int64，32bits cpu用int32
	
	/*/*// 还在回答 long 

	可以不用判断，当初早期只考虑到msvc下long才具有特殊性，其他平台我默认long根据cpu width匹配了，所以优先用了这个，这块可以改进，直接采用 long long 处理成int64也是可以的。

	/*/*/* 解惑 提问者1
	
	
提问者5： 
	我并没有询问如何知道long(tb_long)的宽度，而是询问tb_intX 是如何确定的(我已经知道了)
	
	/*//*/*/ 第二次解释 我不是想了解 long 的宽度 是因为你将 long 作为 int64 的原始类型而已

	首先我知道内置宏的存在

	我之所以问问这么多是因为
	elif defined(__WCHAR_WIDTH__) && (__WCHAR_WIDTH__ == 2) 

	已经使用了 WCHAR_WIDTH ，那为什么不  继续   使用其他内置宏？而是通过cpu位数来判断(我已经知道为什么了)

	/*/**/  既然已经使用 __WCHAR_WIDTH__ 了 继续！ 使用 __LONG_WIDTH__ 不就好了，
	/*//*/  我并没有接触过那么多的系统，
	/*/**/  并不知道 long 的长度和 cpu位数的相关性，
	/*/**/  至少你的优先策略表明在你的经验里 long 长度和cpu位数相关的，
	/*/**/  因为你优先使用 cpu 位数
	
	安装mingw不应该是为了类型，而是为了适配xmake install
	
	/*/**/ 我并没有使用过 xmake，我尝试过指定 sdk，不过太慢了，
	/*/**/ cpu 疯狂计算，我并不认为这个情况是正确的，所以终止了。
	/*/**/ 我并不知道 指定sdk 之后 库的安装路径是对的，
	*/*/*  后来我等待了不知道多长时间，
	/*/**/ 挺长的，可能过了 30s 了吧才开始编译
	
回答者6： 	
	cpubit不也是通过内置宏判断的么？目前的场景cpubit来判断已基本可用，目前没啥问题，就没去通过其他宏判断，之前我也说了，如果后续遇到问题，比如你这的mingw x64环境，如果cpubit搞不定，可以继续通过其他内置宏做进一步判断改进

	/*/*// 只是想知道 是什么  让你优先使用 cpu 位数 而不是 内置宏
	
提问者7：
	
	__SCHAR_WIDTH__
	__SHRT_WIDTH__
	__INT_WIDTH__
	__LONG_WIDTH__
	 
	 /*/** 只是指出我所谓的内置宏是什么，（见 6）
	 
提问者8： 
	
	> 安装mingw不应该是为了类型，而是为了适配xmake install
	还是不明白你要表达什么？

	/*/**/ 我并没有使用过 xmake，我尝试过指定 sdk，不过太慢了，
	/*/*/* cpu 疯狂计算，我并不认为这个情况是正确的，所以终止了。
	/*/*/* 
	/*/*/*  **我并不知道 指定sdk 之后 库的安装路径是对的 **
	/*/*/* 
	/*/*/* 我等待了不知道多长时间，挺长的，可能过了 30s 了吧
	
回答者9：

	还是我之前说过的，我不管__LONG_WIDTH__ 还是 cpubits是否跟long有什么关联，tbox里面基本不用原生long，只用tb_long_t

	/*/*// 又一次提及 long/tb_long，这里再说一边
	
	/*/*/*/*  因为你优先使用 cpu 位数 和 long宽度匹配，所以 当系统的long 是
	/*/*/*/*  8位的时候 int64 是对的，4 位的时候就是错的，所以怎么都和 long
	/*/*/*/*  相关，所以 我可不就重复说long吗，而你就重复解释
	/*/*/*/*  `tbox里面基本不用原生long，只用tb_long_t`

回答者10：
	
		还是不明白你要表达什么？


		/*/*/*/*/ 无所谓
		
提问者11：

	我一直在说 tb_int64_t ，因为上面的代码你使用了 long （我有区分 long ＆ tb_long），所以我一直在说 long

	/*/*/*/*/* 指出我在说 int64 的定义
	/*/*/*/*/* 
	/*/*/*/*/* 不是在说 long 的宽度
	
回答者12：
	
	int64这个 我之前不是已经说过了么
	
	/*/////*/* 注意 11 “我一直在说”，我并没有再次询问关于 long 的事情
	
	我说了 可以改进 通过其他更更合适的内置宏判断也可以 为什么还要去纠结呢。。你可以直接提pr改进下不就好了

提问者13： 

	再次解释

```
